// <auto-generated />
using System;
using Explore.Persistence.Privacy.ErasureAuthority;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Explore.Persistence.PrivacyErasureAuthority.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(EmbeddedPrivacyErasureAuthorityDbContext))]
    [Migration("20260827143730_AddRetainedAuthorityLifecycle")]
    partial class AddRetainedAuthorityLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Explore.Domain.PrivacyErasureCounter", b =>
                {
                    b.Property<bool>("Singleton")
                        .HasColumnType("INTEGER")
                        .HasColumnName("singleton");

                    b.Property<long>("LastSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_sequence");

                    b.Property<long>("RetainedFloorSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("retained_floor_sequence");

                    b.HasKey("Singleton")
                        .HasName("pk_ie_authority_counter");

                    b.ToTable("ie_authority_counter", null, t =>
                        {
                            t.HasCheckConstraint("ck_authority_counter_nonnegative", "last_sequence >= 0");

                            t.HasCheckConstraint("ck_authority_counter_retained_floor", "retained_floor_sequence >= 0 AND retained_floor_sequence <= last_sequence");

                            t.HasCheckConstraint("ck_authority_counter_singleton", "singleton = 1");
                        });
                });

            modelBuilder.Entity("Explore.Domain.PrivacyErasureIntent", b =>
                {
                    b.Property<long>("AuthoritySequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("authority_sequence");

                    b.Property<Guid>("IntentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("intent_id");

                    b.Property<bool>("IsLegalHoldPseudonymized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_legal_hold_pseudonymized");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("policy_version");

                    b.Property<short>("ReasonCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reason_code");

                    b.Property<long>("RecordedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recorded_at_utc");

                    b.Property<long>("RequestedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requested_at_utc");

                    b.Property<long>("RetentionExpiresAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retention_expires_at_utc");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("subject_id");

                    b.Property<short>("SubjectKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subject_kind");

                    b.HasKey("AuthoritySequence")
                        .HasName("pk_ie_erasure_intents");

                    b.HasAlternateKey("IntentId")
                        .HasName("ak_ie_erasure_intents_intent_id");

                    b.HasIndex("IntentId", "SubjectKind", "PolicyVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_ie_erasure_intents_intent_id_subject_kind_policy_version");

                    b.ToTable("ie_erasure_intents", null, t =>
                        {
                            t.HasCheckConstraint("ck_erasure_intents_intent_uuid_v7", "is_legal_hold_pseudonymized = 1 OR substr(intent_id, 15, 1) = '7'");

                            t.HasCheckConstraint("ck_erasure_intents_intent_variant", "lower(substr(intent_id, 20, 1)) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_erasure_intents_policy_version", "policy_version > 0");

                            t.HasCheckConstraint("ck_erasure_intents_reason", "reason_code BETWEEN 1 AND 3");

                            t.HasCheckConstraint("ck_erasure_intents_retention", "retention_expires_at_utc > recorded_at_utc");

                            t.HasCheckConstraint("ck_erasure_intents_sequence", "authority_sequence > 0");

                            t.HasCheckConstraint("ck_erasure_intents_server_time_order", "recorded_at_utc >= requested_at_utc");

                            t.HasCheckConstraint("ck_erasure_intents_subject_kind", "subject_kind = 1");

                            t.HasCheckConstraint("ck_erasure_intents_subject_nonempty", "subject_id <> '00000000-0000-0000-0000-000000000000'");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
