// <auto-generated />
using System;
using Explore.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Explore.Persistence.Migrations
{
    [DbContext(typeof(ExploreDbContext))]
    [Migration("20251211174701_AddEventDates")]
    partial class AddEventDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Explore.Domain.AudienceAge", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("integer")
                        .HasColumnName("max_age");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer")
                        .HasColumnName("min_age");

                    b.HasKey("Id")
                        .HasName("pk_audience_ages");

                    b.ToTable("audience_ages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "All Ages"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Adults Only (18+)",
                            MinAge = 18
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Teens & Adults (16+)",
                            MinAge = 16
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Preteens & Up (12+)",
                            MinAge = 12
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Young Children (0-6)",
                            MaxAge = 6
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Children (0-12)",
                            MaxAge = 12
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Children & Young Teens (0-16)",
                            MaxAge = 16
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Youth (0-18)",
                            MaxAge = 18
                        });
                });

            modelBuilder.Entity("Explore.Domain.AudienceGender", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id")
                        .HasName("pk_audience_genders");

                    b.ToTable("audience_genders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Man"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Woman"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Both"
                        });
                });

            modelBuilder.Entity("Explore.Domain.EducationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id")
                        .HasName("pk_education_types");

                    b.ToTable("education_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "School"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Institut"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Course"
                        });
                });

            modelBuilder.Entity("Explore.Domain.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id")
                        .HasName("pk_event_types");

                    b.ToTable("event_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Conference"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Webinar"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Workshop"
                        });
                });

            modelBuilder.Entity("Explore.Domain.FileType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id")
                        .HasName("pk_file_type");

                    b.ToTable("file_type", (string)null);
                });

            modelBuilder.Entity("Explore.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int>("Postcode")
                        .HasColumnType("integer")
                        .HasColumnName("postcode");

                    b.Property<int>("StatusTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status_type_id");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("StatusTypeId")
                        .HasDatabaseName("ix_organizations_status_type_id");

                    b.ToTable("organizations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("018e4e5c-7f00-7000-8000-000000000001"),
                            Address = "Parc Du Peterbos ...",
                            City = "Brussels",
                            Country = "Belgium",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contact@openislamu.org",
                            FullName = "ISLAMU",
                            Postcode = 1070,
                            StatusTypeId = 2,
                            WebsiteUrl = "https://islamu.ngo"
                        });
                });

            modelBuilder.Entity("Explore.Domain.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_members");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_organization_members_organization_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_members_user_id");

                    b.ToTable("organization_members", (string)null);
                });

            modelBuilder.Entity("Explore.Domain.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("AudienceAgeId")
                        .HasColumnType("integer")
                        .HasColumnName("audience_age_id");

                    b.Property<int?>("AudienceAttendees")
                        .HasColumnType("integer")
                        .HasColumnName("audience_attendees");

                    b.Property<int>("AudienceGenderId")
                        .HasColumnType("integer")
                        .HasColumnName("audience_gender_id");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("FeaturedImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("featured_image_id");

                    b.Property<bool?>("IsRegistrationRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_registration_required");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int?>("PostCode")
                        .HasColumnType("integer")
                        .HasColumnName("post_code");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<int>("ProgramTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("program_type_id");

                    b.Property<string>("ProgramUrl")
                        .HasColumnType("text")
                        .HasColumnName("program_url");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TotalViews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_views");

                    b.HasKey("Id");

                    b.HasIndex("AudienceAgeId")
                        .HasDatabaseName("ix_programs_audience_age_id");

                    b.HasIndex("AudienceGenderId")
                        .HasDatabaseName("ix_programs_audience_gender_id");

                    b.HasIndex("FeaturedImageId")
                        .HasDatabaseName("ix_programs_featured_image_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_programs_organization_id");

                    b.HasIndex("ProgramTypeId")
                        .HasDatabaseName("ix_programs_program_type_id");

                    b.ToTable("programs", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Explore.Domain.ProgramRegistartion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<int>("StatusTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("status_type_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_program_registartions");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("ix_program_registartions_program_id");

                    b.HasIndex("StatusTypeId")
                        .HasDatabaseName("ix_program_registartions_status_type_id");

                    b.ToTable("program_registartions", (string)null);
                });

            modelBuilder.Entity("Explore.Domain.ProgramType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id")
                        .HasName("pk_program_types");

                    b.ToTable("program_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Events like Conferences, Webinars, Workshops & More!",
                            FullName = "Event"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Educations like Schools, Bootcamps & More!",
                            FullName = "Education"
                        });
                });

            modelBuilder.Entity("Explore.Domain.StatusType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id")
                        .HasName("pk_status_types");

                    b.ToTable("status_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Status is pending approval of Admin verifying the Existence of Legal Entity",
                            FullName = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Status has been approved by Admin after verifying the Existence of Legal Entity",
                            FullName = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Status has been rejected by Admin after failing to verify the Existence of Legal Entity",
                            FullName = "Rejected"
                        });
                });

            modelBuilder.Entity("Explore.Domain.StorageObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extension");

                    b.Property<int>("FileTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("file_type_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.HasIndex("FileTypeId")
                        .HasDatabaseName("ix_files_file_type_id");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("Explore.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Explore.Domain.Education", b =>
                {
                    b.HasBaseType("Explore.Domain.Program");

                    b.Property<int>("EducationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("education_type_id");

                    b.HasIndex("EducationTypeId")
                        .HasDatabaseName("ix_educations_education_type_id");

                    b.ToTable("educations", (string)null);
                });

            modelBuilder.Entity("Explore.Domain.Event", b =>
                {
                    b.HasBaseType("Explore.Domain.Program");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("event_type_id");

                    b.HasIndex("EventTypeId")
                        .HasDatabaseName("ix_events_event_type_id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Explore.Domain.Organization", b =>
                {
                    b.HasOne("Explore.Domain.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organizations_status_types_status_type_id");

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("Explore.Domain.OrganizationMember", b =>
                {
                    b.HasOne("Explore.Domain.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_members_organizations_organization_id");

                    b.HasOne("Explore.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_organization_members_users_user_id");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Explore.Domain.Program", b =>
                {
                    b.HasOne("Explore.Domain.AudienceAge", "AudienceAge")
                        .WithMany()
                        .HasForeignKey("AudienceAgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_programs_audience_ages_audience_age_id");

                    b.HasOne("Explore.Domain.AudienceGender", "AudienceGender")
                        .WithMany()
                        .HasForeignKey("AudienceGenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_programs_audience_genders_audience_gender_id");

                    b.HasOne("Explore.Domain.StorageObject", "FeaturedImage")
                        .WithMany()
                        .HasForeignKey("FeaturedImageId")
                        .HasConstraintName("fk_programs_files_featured_image_id");

                    b.HasOne("Explore.Domain.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_programs_organizations_organization_id");

                    b.HasOne("Explore.Domain.ProgramType", "ProgramType")
                        .WithMany()
                        .HasForeignKey("ProgramTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_programs_program_types_program_type_id");

                    b.Navigation("AudienceAge");

                    b.Navigation("AudienceGender");

                    b.Navigation("FeaturedImage");

                    b.Navigation("Organization");

                    b.Navigation("ProgramType");
                });

            modelBuilder.Entity("Explore.Domain.ProgramRegistartion", b =>
                {
                    b.HasOne("Explore.Domain.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_program_registartions_programs_program_id");

                    b.HasOne("Explore.Domain.StatusType", "StatusType")
                        .WithMany()
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_program_registartions_status_types_status_type_id");

                    b.Navigation("Program");

                    b.Navigation("StatusType");
                });

            modelBuilder.Entity("Explore.Domain.StorageObject", b =>
                {
                    b.HasOne("Explore.Domain.FileType", "FileType")
                        .WithMany()
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_files_file_type_file_type_id");

                    b.Navigation("FileType");
                });

            modelBuilder.Entity("Explore.Domain.Education", b =>
                {
                    b.HasOne("Explore.Domain.EducationType", "EducationType")
                        .WithMany()
                        .HasForeignKey("EducationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_educations_education_types_education_type_id");

                    b.HasOne("Explore.Domain.Program", null)
                        .WithOne()
                        .HasForeignKey("Explore.Domain.Education", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_educations_programs_id");

                    b.Navigation("EducationType");
                });

            modelBuilder.Entity("Explore.Domain.Event", b =>
                {
                    b.HasOne("Explore.Domain.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_events_event_types_event_type_id");

                    b.HasOne("Explore.Domain.Program", null)
                        .WithOne()
                        .HasForeignKey("Explore.Domain.Event", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_events_programs_id");

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("Explore.Domain.Organization", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
