// ABOUTME: System.Text.Json source generator context for AOT compilation.
// Enables compile-time JSON serialization code generation, eliminating reflection overhead.
// This improves WASM bundle size and runtime performance for Blazor WebAssembly.

using System.Text.Json.Serialization;
using Explore.Blazor.Client.Clients;
using Explore.Blazor.Client.Models;
using Explore.Blazor.Client.Models.Responses;
using Explore.Blazor.Client.Pages.Events;

namespace Explore.Blazor.Client.Serialization;

/// <summary>
/// System.Text.Json source generator context for AOT-friendly JSON serialization.
/// Includes all DTOs used by the NSwag-generated EventApiClient and Blazor UI models.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false,
    AllowTrailingCommas = true)]
[JsonSerializable(typeof(ActorDto))]
[JsonSerializable(typeof(ActorKeyStoreDto))]
[JsonSerializable(typeof(ActorKeyStoreListDto))]
[JsonSerializable(typeof(ActorListDto))]
[JsonSerializable(typeof(ActorTypeDto))]
[JsonSerializable(typeof(ActorTypeListDto))]
[JsonSerializable(typeof(AddOrganizationMemberDto))]
[JsonSerializable(typeof(AtprotoRecordDto))]
[JsonSerializable(typeof(AtprotoRecordListDto))]
[JsonSerializable(typeof(AudienceAgeDto))]
[JsonSerializable(typeof(AudienceAgeListDto))]
[JsonSerializable(typeof(AudienceGenderDto))]
[JsonSerializable(typeof(AudienceGenderListDto))]
[JsonSerializable(typeof(BaseCommandResponseOfGuid))]
[JsonSerializable(typeof(BaseCommandResponseOfboolean))]
[JsonSerializable(typeof(BaseCommandResponseOfint))]
[JsonSerializable(typeof(BaseCommandResponseOfstring))]
[JsonSerializable(typeof(CategoryDto))]
[JsonSerializable(typeof(CategoryListDto))]
[JsonSerializable(typeof(CreateActorDto))]
[JsonSerializable(typeof(CreateActorKeyStoreDto))]
[JsonSerializable(typeof(CreateAtprotoRecordDto))]
[JsonSerializable(typeof(CreateCategoryDto))]
[JsonSerializable(typeof(CreateEventAgendaItemRequest))]
[JsonSerializable(typeof(CreateEventDayRequest))]
[JsonSerializable(typeof(CreateEventRequest))]
[JsonSerializable(typeof(CreateEventRegistrationDto))]
[JsonSerializable(typeof(CreateEventRoomRequest))]
[JsonSerializable(typeof(CreateEventSessionAgendaItemDto))]
[JsonSerializable(typeof(CreateEventSessionDto))]
[JsonSerializable(typeof(CreateEventSessionRequest))]
[JsonSerializable(typeof(CreateIndexedDidDto))]
[JsonSerializable(typeof(CreateLocationDto))]
[JsonSerializable(typeof(CreateOrganizationDto))]
[JsonSerializable(typeof(CreateOrganizationReviewDto))]
[JsonSerializable(typeof(CreateStorageObjectDto))]
[JsonSerializable(typeof(CreateSyncStateDto))]
[JsonSerializable(typeof(CreateTagDto))]
[JsonSerializable(typeof(CreateTenantDto))]
[JsonSerializable(typeof(CreateTenantNavigationLinkDto))]
[JsonSerializable(typeof(CreateUpdateIslamicAspectDto))]
[JsonSerializable(typeof(CreateUpdateTechAspectDto))]
[JsonSerializable(typeof(CreateUserAuthenticationTokenDto))]
[JsonSerializable(typeof(CreateUserExternalLoginDto))]
[JsonSerializable(typeof(DidCustodyTypeDto))]
[JsonSerializable(typeof(DidCustodyTypeListDto))]
[JsonSerializable(typeof(EventDto))]
[JsonSerializable(typeof(EventCreationContextDto))]
[JsonSerializable(typeof(EventCreationPublisherOptionDto))]
[JsonSerializable(typeof(EventFormatDto))]
[JsonSerializable(typeof(EventFormatListDto))]
[JsonSerializable(typeof(EventIslamicAspectDto))]
[JsonSerializable(typeof(EventListDto))]
[JsonSerializable(typeof(EventDetail.EventDetailState))]
[JsonSerializable(typeof(EventRegistrationDto))]
[JsonSerializable(typeof(EventRegistrationListDto))]
[JsonSerializable(typeof(EventSessionAgendaItemDto))]
[JsonSerializable(typeof(EventSessionAgendaItemListDto))]
[JsonSerializable(typeof(EventSessionDto))]
[JsonSerializable(typeof(EventSessionLanguageDto))]
[JsonSerializable(typeof(EventSessionLanguageListDto))]
[JsonSerializable(typeof(EventSessionListDto))]
[JsonSerializable(typeof(EventSessionSpeakerDto))]
[JsonSerializable(typeof(EventSessionSpeakerListDto))]
[JsonSerializable(typeof(EventStatusDto))]
[JsonSerializable(typeof(EventStatusListDto))]
[JsonSerializable(typeof(EventTechAspectDto))]
[JsonSerializable(typeof(EventTypeListDto))]
[JsonSerializable(typeof(FileTypeDto))]
[JsonSerializable(typeof(FileTypeListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfActorListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfCategoryListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfEventListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfEventSessionListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfIndexedDidListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfLocationListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfOrganizationListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfOrganizationReviewDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfTagListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfActorListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfCategoryListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfEventListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfEventSessionListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfIndexedDidListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfLocationListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfOrganizationListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfOrganizationReviewDto))]
[JsonSerializable(typeof(HalCollectionResourceOfTagListDto))]
[JsonSerializable(typeof(HalLink))]
[JsonSerializable(typeof(HalResourceOfActorDto))]
[JsonSerializable(typeof(HalResourceOfCategoryDto))]
[JsonSerializable(typeof(HalResourceOfEventDto))]
[JsonSerializable(typeof(HalResourceOfEventSessionDto))]
[JsonSerializable(typeof(HalResourceOfIndexedDidDto))]
[JsonSerializable(typeof(HalResourceOfLocationDto))]
[JsonSerializable(typeof(HalResourceOfOrganizationDto))]
[JsonSerializable(typeof(HalResourceOfTagDto))]
[JsonSerializable(typeof(InstanceOnboardingStatusDto))]
[JsonSerializable(typeof(LanguageDto))]
[JsonSerializable(typeof(LanguageListDto))]
[JsonSerializable(typeof(LocationDto))]
[JsonSerializable(typeof(LocationListDto))]
[JsonSerializable(typeof(MadhabDto))]
[JsonSerializable(typeof(MadhabListDto))]
[JsonSerializable(typeof(ModuleActionResponse))]
[JsonSerializable(typeof(ModuleEnabledResponse))]
[JsonSerializable(typeof(ModuleInfo))]
[JsonSerializable(typeof(ModuleSchemaResponse))]
[JsonSerializable(typeof(OrganizationDto))]
[JsonSerializable(typeof(OrganizationInvitationDto))]
[JsonSerializable(typeof(OrganizationListDto))]
[JsonSerializable(typeof(OrganizationMemberDto))]
[JsonSerializable(typeof(OrganizationPositionDto))]
[JsonSerializable(typeof(OrganizationPositionListDto))]
[JsonSerializable(typeof(OrganizationReviewDto))]
[JsonSerializable(typeof(PaginatedResultOfEventRegistrationListDto))]
[JsonSerializable(typeof(PaginatedResultOfEventSessionAgendaItemListDto))]
[JsonSerializable(typeof(PaginatedResultOfStorageObjectListDto))]
[JsonSerializable(typeof(PresignedDownloadUrlResponseDto))]
[JsonSerializable(typeof(ProblemDetails))]
[JsonSerializable(typeof(PublicExperienceSettingsDto))]
[JsonSerializable(typeof(RegistrationModeDto))]
[JsonSerializable(typeof(RegistrationModeListDto))]
[JsonSerializable(typeof(StatusTypeListDto))]
[JsonSerializable(typeof(StorageObjectDto))]
[JsonSerializable(typeof(StorageObjectListDto))]
[JsonSerializable(typeof(SyncStateDto))]
[JsonSerializable(typeof(SyncStateListDto))]
[JsonSerializable(typeof(TagDto))]
[JsonSerializable(typeof(TagListDto))]
[JsonSerializable(typeof(TagTypeDto))]
[JsonSerializable(typeof(TagTypeListDto))]
[JsonSerializable(typeof(TenantDto))]
[JsonSerializable(typeof(TenantListDto))]
[JsonSerializable(typeof(TenantNavigationLinkDto))]
[JsonSerializable(typeof(TenantOnboardingStatusDto))]
[JsonSerializable(typeof(TenantPolicySettingsDto))]
[JsonSerializable(typeof(UpdateActorDto))]
[JsonSerializable(typeof(UpdateActorKeyStoreDto))]
[JsonSerializable(typeof(UpdateAtprotoRecordDto))]
[JsonSerializable(typeof(UpdateCategoryDto))]
[JsonSerializable(typeof(UpdateEventDto))]
[JsonSerializable(typeof(UpdateEventRegistrationDto))]
[JsonSerializable(typeof(UpdateEventSessionAgendaItemDto))]
[JsonSerializable(typeof(UpdateEventSessionDto))]
[JsonSerializable(typeof(UpdateIndexedDidDto))]
[JsonSerializable(typeof(UpdateLocationDto))]
[JsonSerializable(typeof(UpdateOrganizationApprovalStatusDto))]
[JsonSerializable(typeof(UpdateOrganizationDto))]
[JsonSerializable(typeof(UpdateOrganizationMemberRoleDto))]
[JsonSerializable(typeof(UpdateStorageObjectDto))]
[JsonSerializable(typeof(UpdateSyncStateDto))]
[JsonSerializable(typeof(UpdateTagDto))]
[JsonSerializable(typeof(UpdateTenantDto))]
[JsonSerializable(typeof(UpdateTenantNavigationLinkDto))]
[JsonSerializable(typeof(UpdateTenantNavigationLinkOrderDto))]
[JsonSerializable(typeof(UpdateUserAuthenticationTokenDto))]
[JsonSerializable(typeof(UpdateUserDto))]
[JsonSerializable(typeof(UpdateUserExternalLoginDto))]
[JsonSerializable(typeof(UploadRequestDto))]
[JsonSerializable(typeof(UploadUrlResponseDto))]
[JsonSerializable(typeof(UserAuthenticationTokenDto))]
[JsonSerializable(typeof(UserAuthenticationTokenListDto))]
[JsonSerializable(typeof(UserDto))]
[JsonSerializable(typeof(UserExternalLoginDto))]
[JsonSerializable(typeof(UserExternalLoginListDto))]
[JsonSerializable(typeof(VisibilityTypeDto))]
[JsonSerializable(typeof(VisibilityTypeListDto))]
// Blazor Client Models
[JsonSerializable(typeof(ServiceResult))]
[JsonSerializable(typeof(TenantContext))]
[JsonSerializable(typeof(UserInfo))]
public partial class AppJsonSerializerContext : JsonSerializerContext
{
}
