-- ABOUTME: Idempotent SQLite DDL for the co-located Quartz.NET scheduler tables in the primary application database.
-- ABOUTME: {prefix} is substituted with the validated Scheduler:Quartz:TablePrefix; GO on its own line separates batches.

CREATE TABLE IF NOT EXISTS {prefix}JOB_DETAILS (
    SCHED_NAME TEXT NOT NULL,
    JOB_NAME TEXT NOT NULL,
    JOB_GROUP TEXT NOT NULL,
    DESCRIPTION TEXT NULL,
    JOB_CLASS_NAME TEXT NOT NULL,
    IS_DURABLE INTEGER NOT NULL,
    IS_NONCONCURRENT INTEGER NOT NULL,
    IS_UPDATE_DATA INTEGER NOT NULL,
    REQUESTS_RECOVERY INTEGER NOT NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
)
GO

CREATE TABLE IF NOT EXISTS {prefix}TRIGGERS (
    SCHED_NAME TEXT NOT NULL,
    TRIGGER_NAME TEXT NOT NULL,
    TRIGGER_GROUP TEXT NOT NULL,
    JOB_NAME TEXT NOT NULL,
    JOB_GROUP TEXT NOT NULL,
    DESCRIPTION TEXT NULL,
    NEXT_FIRE_TIME INTEGER NULL,
    PREV_FIRE_TIME INTEGER NULL,
    PRIORITY INTEGER NULL,
    TRIGGER_STATE TEXT NOT NULL,
    TRIGGER_TYPE TEXT NOT NULL,
    START_TIME INTEGER NOT NULL,
    END_TIME INTEGER NULL,
    CALENDAR_NAME TEXT NULL,
    MISFIRE_INSTR INTEGER NULL,
    MISFIRE_ORIG_FIRE_TIME INTEGER NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
        REFERENCES {prefix}JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP)
)
GO

CREATE TABLE IF NOT EXISTS {prefix}SIMPLE_TRIGGERS (
    SCHED_NAME TEXT NOT NULL,
    TRIGGER_NAME TEXT NOT NULL,
    TRIGGER_GROUP TEXT NOT NULL,
    REPEAT_COUNT INTEGER NOT NULL,
    REPEAT_INTERVAL INTEGER NOT NULL,
    TIMES_TRIGGERED INTEGER NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES {prefix}TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
)
GO

CREATE TABLE IF NOT EXISTS {prefix}CRON_TRIGGERS (
    SCHED_NAME TEXT NOT NULL,
    TRIGGER_NAME TEXT NOT NULL,
    TRIGGER_GROUP TEXT NOT NULL,
    CRON_EXPRESSION TEXT NOT NULL,
    TIME_ZONE_ID TEXT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES {prefix}TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
)
GO

CREATE TABLE IF NOT EXISTS {prefix}SIMPROP_TRIGGERS (
    SCHED_NAME TEXT NOT NULL,
    TRIGGER_NAME TEXT NOT NULL,
    TRIGGER_GROUP TEXT NOT NULL,
    STR_PROP_1 TEXT NULL,
    STR_PROP_2 TEXT NULL,
    STR_PROP_3 TEXT NULL,
    INT_PROP_1 INTEGER NULL,
    INT_PROP_2 INTEGER NULL,
    LONG_PROP_1 INTEGER NULL,
    LONG_PROP_2 INTEGER NULL,
    DEC_PROP_1 NUMERIC NULL,
    DEC_PROP_2 NUMERIC NULL,
    BOOL_PROP_1 INTEGER NULL,
    BOOL_PROP_2 INTEGER NULL,
    TIME_ZONE_ID TEXT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES {prefix}TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
)
GO

CREATE TABLE IF NOT EXISTS {prefix}BLOB_TRIGGERS (
    SCHED_NAME TEXT NOT NULL,
    TRIGGER_NAME TEXT NOT NULL,
    TRIGGER_GROUP TEXT NOT NULL,
    BLOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES {prefix}TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
)
GO

CREATE TABLE IF NOT EXISTS {prefix}CALENDARS (
    SCHED_NAME TEXT NOT NULL,
    CALENDAR_NAME TEXT NOT NULL,
    CALENDAR BLOB NOT NULL,
    PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
)
GO

CREATE TABLE IF NOT EXISTS {prefix}PAUSED_TRIGGER_GRPS (
    SCHED_NAME TEXT NOT NULL,
    TRIGGER_GROUP TEXT NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
)
GO

CREATE TABLE IF NOT EXISTS {prefix}FIRED_TRIGGERS (
    SCHED_NAME TEXT NOT NULL,
    ENTRY_ID TEXT NOT NULL,
    TRIGGER_NAME TEXT NOT NULL,
    TRIGGER_GROUP TEXT NOT NULL,
    INSTANCE_NAME TEXT NOT NULL,
    FIRED_TIME INTEGER NOT NULL,
    SCHED_TIME INTEGER NOT NULL,
    PRIORITY INTEGER NOT NULL,
    STATE TEXT NOT NULL,
    JOB_NAME TEXT NULL,
    JOB_GROUP TEXT NULL,
    IS_NONCONCURRENT INTEGER NULL,
    REQUESTS_RECOVERY INTEGER NULL,
    PRIMARY KEY (SCHED_NAME, ENTRY_ID)
)
GO

CREATE TABLE IF NOT EXISTS {prefix}SCHEDULER_STATE (
    SCHED_NAME TEXT NOT NULL,
    INSTANCE_NAME TEXT NOT NULL,
    LAST_CHECKIN_TIME INTEGER NOT NULL,
    CHECKIN_INTERVAL INTEGER NOT NULL,
    PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
)
GO

CREATE TABLE IF NOT EXISTS {prefix}LOCKS (
    SCHED_NAME TEXT NOT NULL,
    LOCK_NAME TEXT NOT NULL,
    PRIMARY KEY (SCHED_NAME, LOCK_NAME)
)
GO

CREATE INDEX IF NOT EXISTS IX_{prefix}TRIGGERS_JOB
    ON {prefix}TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP)
GO

CREATE INDEX IF NOT EXISTS IX_{prefix}TRIGGERS_STATE_NEXT_FIRE
    ON {prefix}TRIGGERS (SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME)
GO

CREATE INDEX IF NOT EXISTS IX_{prefix}FIRED_TRIGGERS_INSTANCE
    ON {prefix}FIRED_TRIGGERS (SCHED_NAME, INSTANCE_NAME)
GO

CREATE INDEX IF NOT EXISTS IX_{prefix}FIRED_TRIGGERS_JOB
    ON {prefix}FIRED_TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP)
GO

CREATE INDEX IF NOT EXISTS IX_{prefix}FIRED_TRIGGERS_TRIGGER
    ON {prefix}FIRED_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
GO
