-- ABOUTME: Idempotent SQL Server DDL for the co-located Quartz.NET scheduler tables in the primary application database.
-- ABOUTME: {prefix} is substituted with the validated Scheduler:Quartz:TablePrefix; GO on its own line separates batches.

IF OBJECT_ID(N'{prefix}JOB_DETAILS', N'U') IS NULL
CREATE TABLE {prefix}JOB_DETAILS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    JOB_NAME NVARCHAR(200) NOT NULL,
    JOB_GROUP NVARCHAR(200) NOT NULL,
    DESCRIPTION NVARCHAR(250) NULL,
    JOB_CLASS_NAME NVARCHAR(250) NOT NULL,
    IS_DURABLE BIT NOT NULL,
    IS_NONCONCURRENT BIT NOT NULL,
    IS_UPDATE_DATA BIT NOT NULL,
    REQUESTS_RECOVERY BIT NOT NULL,
    JOB_DATA VARBINARY(MAX) NULL,
    PRIMARY KEY CLUSTERED (SCHED_NAME, JOB_NAME, JOB_GROUP)
)
GO

IF OBJECT_ID(N'{prefix}TRIGGERS', N'U') IS NULL
CREATE TABLE {prefix}TRIGGERS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    TRIGGER_NAME NVARCHAR(200) NOT NULL,
    TRIGGER_GROUP NVARCHAR(200) NOT NULL,
    JOB_NAME NVARCHAR(200) NOT NULL,
    JOB_GROUP NVARCHAR(200) NOT NULL,
    DESCRIPTION NVARCHAR(250) NULL,
    NEXT_FIRE_TIME BIGINT NULL,
    PREV_FIRE_TIME BIGINT NULL,
    PRIORITY INT NULL,
    TRIGGER_STATE NVARCHAR(16) NOT NULL,
    TRIGGER_TYPE NVARCHAR(8) NOT NULL,
    START_TIME BIGINT NOT NULL,
    END_TIME BIGINT NULL,
    CALENDAR_NAME NVARCHAR(200) NULL,
    MISFIRE_INSTR SMALLINT NULL,
    MISFIRE_ORIG_FIRE_TIME BIGINT NULL,
    JOB_DATA VARBINARY(MAX) NULL,
    PRIMARY KEY CLUSTERED (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
        REFERENCES {prefix}JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP)
)
GO

IF OBJECT_ID(N'{prefix}SIMPLE_TRIGGERS', N'U') IS NULL
CREATE TABLE {prefix}SIMPLE_TRIGGERS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    TRIGGER_NAME NVARCHAR(200) NOT NULL,
    TRIGGER_GROUP NVARCHAR(200) NOT NULL,
    REPEAT_COUNT BIGINT NOT NULL,
    REPEAT_INTERVAL BIGINT NOT NULL,
    TIMES_TRIGGERED BIGINT NOT NULL,
    PRIMARY KEY CLUSTERED (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES {prefix}TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
)
GO

IF OBJECT_ID(N'{prefix}CRON_TRIGGERS', N'U') IS NULL
CREATE TABLE {prefix}CRON_TRIGGERS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    TRIGGER_NAME NVARCHAR(200) NOT NULL,
    TRIGGER_GROUP NVARCHAR(200) NOT NULL,
    CRON_EXPRESSION NVARCHAR(120) NOT NULL,
    TIME_ZONE_ID NVARCHAR(80) NULL,
    PRIMARY KEY CLUSTERED (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES {prefix}TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
)
GO

IF OBJECT_ID(N'{prefix}SIMPROP_TRIGGERS', N'U') IS NULL
CREATE TABLE {prefix}SIMPROP_TRIGGERS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    TRIGGER_NAME NVARCHAR(200) NOT NULL,
    TRIGGER_GROUP NVARCHAR(200) NOT NULL,
    STR_PROP_1 NVARCHAR(512) NULL,
    STR_PROP_2 NVARCHAR(512) NULL,
    STR_PROP_3 NVARCHAR(512) NULL,
    INT_PROP_1 INT NULL,
    INT_PROP_2 INT NULL,
    LONG_PROP_1 BIGINT NULL,
    LONG_PROP_2 BIGINT NULL,
    DEC_PROP_1 NUMERIC(13, 4) NULL,
    DEC_PROP_2 NUMERIC(13, 4) NULL,
    BOOL_PROP_1 BIT NULL,
    BOOL_PROP_2 BIT NULL,
    TIME_ZONE_ID NVARCHAR(80) NULL,
    PRIMARY KEY CLUSTERED (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES {prefix}TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
)
GO

IF OBJECT_ID(N'{prefix}BLOB_TRIGGERS', N'U') IS NULL
CREATE TABLE {prefix}BLOB_TRIGGERS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    TRIGGER_NAME NVARCHAR(200) NOT NULL,
    TRIGGER_GROUP NVARCHAR(200) NOT NULL,
    BLOB_DATA VARBINARY(MAX) NULL,
    PRIMARY KEY CLUSTERED (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES {prefix}TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
)
GO

IF OBJECT_ID(N'{prefix}CALENDARS', N'U') IS NULL
CREATE TABLE {prefix}CALENDARS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    CALENDAR_NAME NVARCHAR(200) NOT NULL,
    CALENDAR VARBINARY(MAX) NOT NULL,
    PRIMARY KEY CLUSTERED (SCHED_NAME, CALENDAR_NAME)
)
GO

IF OBJECT_ID(N'{prefix}PAUSED_TRIGGER_GRPS', N'U') IS NULL
CREATE TABLE {prefix}PAUSED_TRIGGER_GRPS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    TRIGGER_GROUP NVARCHAR(200) NOT NULL,
    PRIMARY KEY CLUSTERED (SCHED_NAME, TRIGGER_GROUP)
)
GO

IF OBJECT_ID(N'{prefix}FIRED_TRIGGERS', N'U') IS NULL
CREATE TABLE {prefix}FIRED_TRIGGERS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    ENTRY_ID NVARCHAR(140) NOT NULL,
    TRIGGER_NAME NVARCHAR(200) NOT NULL,
    TRIGGER_GROUP NVARCHAR(200) NOT NULL,
    INSTANCE_NAME NVARCHAR(200) NOT NULL,
    FIRED_TIME BIGINT NOT NULL,
    SCHED_TIME BIGINT NOT NULL,
    PRIORITY INT NOT NULL,
    STATE NVARCHAR(16) NOT NULL,
    JOB_NAME NVARCHAR(200) NULL,
    JOB_GROUP NVARCHAR(200) NULL,
    IS_NONCONCURRENT BIT NULL,
    REQUESTS_RECOVERY BIT NULL,
    PRIMARY KEY CLUSTERED (SCHED_NAME, ENTRY_ID)
)
GO

IF OBJECT_ID(N'{prefix}SCHEDULER_STATE', N'U') IS NULL
CREATE TABLE {prefix}SCHEDULER_STATE (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    INSTANCE_NAME NVARCHAR(200) NOT NULL,
    LAST_CHECKIN_TIME BIGINT NOT NULL,
    CHECKIN_INTERVAL BIGINT NOT NULL,
    PRIMARY KEY CLUSTERED (SCHED_NAME, INSTANCE_NAME)
)
GO

IF OBJECT_ID(N'{prefix}LOCKS', N'U') IS NULL
CREATE TABLE {prefix}LOCKS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    LOCK_NAME NVARCHAR(40) NOT NULL,
    PRIMARY KEY CLUSTERED (SCHED_NAME, LOCK_NAME)
)
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_{prefix}TRIGGERS_JOB' AND object_id = OBJECT_ID(N'{prefix}TRIGGERS'))
CREATE NONCLUSTERED INDEX IX_{prefix}TRIGGERS_JOB
    ON {prefix}TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP)
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_{prefix}TRIGGERS_STATE_NEXT_FIRE' AND object_id = OBJECT_ID(N'{prefix}TRIGGERS'))
CREATE NONCLUSTERED INDEX IX_{prefix}TRIGGERS_STATE_NEXT_FIRE
    ON {prefix}TRIGGERS (SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME)
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_{prefix}FIRED_TRIGGERS_INSTANCE' AND object_id = OBJECT_ID(N'{prefix}FIRED_TRIGGERS'))
CREATE NONCLUSTERED INDEX IX_{prefix}FIRED_TRIGGERS_INSTANCE
    ON {prefix}FIRED_TRIGGERS (SCHED_NAME, INSTANCE_NAME)
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_{prefix}FIRED_TRIGGERS_JOB' AND object_id = OBJECT_ID(N'{prefix}FIRED_TRIGGERS'))
CREATE NONCLUSTERED INDEX IX_{prefix}FIRED_TRIGGERS_JOB
    ON {prefix}FIRED_TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP)
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_{prefix}FIRED_TRIGGERS_TRIGGER' AND object_id = OBJECT_ID(N'{prefix}FIRED_TRIGGERS'))
CREATE NONCLUSTERED INDEX IX_{prefix}FIRED_TRIGGERS_TRIGGER
    ON {prefix}FIRED_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
GO
