// ABOUTME: Source-generated JSON metadata for event-management MCP descriptors.
// ABOUTME: Keeps event MCP serialization deterministic without broad reflection fallback.

using System.Text.Json.Serialization;

namespace Explore.API.Mcp;

[JsonSerializable(typeof(EventMcpSearchResultDescriptor))]
[JsonSerializable(typeof(EventMcpMyEventsResultDescriptor))]
[JsonSerializable(typeof(EventMcpCreationContextDescriptor))]
[JsonSerializable(typeof(EventMcpCreationPublisherOptionDescriptor))]
[JsonSerializable(typeof(EventMcpManagementContextResultDescriptor))]
[JsonSerializable(typeof(EventMcpManagementContextDescriptor))]
[JsonSerializable(typeof(EventMcpManagementActionDescriptor))]
[JsonSerializable(typeof(EventMcpPublishReadinessDescriptor))]
[JsonSerializable(typeof(EventMcpPublishReadinessIssueDescriptor))]
[JsonSerializable(typeof(EventMcpPublishReadinessResultDescriptor))]
[JsonSerializable(typeof(EventMcpProgramManagementResultDescriptor))]
[JsonSerializable(typeof(EventMcpProgramManagementContextDescriptor))]
[JsonSerializable(typeof(EventMcpSessionGroupDescriptor))]
[JsonSerializable(typeof(EventMcpDayDescriptor))]
[JsonSerializable(typeof(EventMcpAgendaItemDescriptor))]
[JsonSerializable(typeof(EventMcpCustomPropertiesResultDescriptor))]
[JsonSerializable(typeof(EventMcpCustomPropertiesContextDescriptor))]
[JsonSerializable(typeof(EventMcpCustomPropertyDefinitionDescriptor))]
[JsonSerializable(typeof(EventMcpCustomPropertyValueDescriptor))]
[JsonSerializable(typeof(EventMcpRegistrationsContextResultDescriptor))]
[JsonSerializable(typeof(EventMcpRegistrationsContextDescriptor))]
[JsonSerializable(typeof(EventMcpRegistrationDescriptor))]
[JsonSerializable(typeof(EventMcpTeamContextResultDescriptor))]
[JsonSerializable(typeof(EventMcpTeamContextDescriptor))]
[JsonSerializable(typeof(EventMcpCurrentUserPermissionsDescriptor))]
[JsonSerializable(typeof(EventMcpTeamMemberDescriptor))]
[JsonSerializable(typeof(EventMcpRolePresetDescriptor))]
[JsonSerializable(typeof(EventMcpTemplateCatalogResultDescriptor))]
[JsonSerializable(typeof(EventMcpTemplateCatalogContextDescriptor))]
[JsonSerializable(typeof(EventMcpTemplateDescriptor))]
[JsonSerializable(typeof(EventMcpSessionTemplateCatalogPageDescriptor))]
[JsonSerializable(typeof(EventMcpSessionTemplateDescriptor))]
[JsonSerializable(typeof(EventMcpTemplateSyncContextResultDescriptor))]
[JsonSerializable(typeof(EventMcpTemplateSyncContextDescriptor))]
[JsonSerializable(typeof(EventMcpSessionTemplateSyncContextResultDescriptor))]
[JsonSerializable(typeof(EventMcpSessionTemplateSyncContextDescriptor))]
[JsonSerializable(typeof(EventMcpTemplateDiffDescriptor))]
[JsonSerializable(typeof(EventMcpTemplateSyncHistoryPageDescriptor))]
[JsonSerializable(typeof(EventMcpTemplateSyncHistoryItemDescriptor))]
[JsonSerializable(typeof(EventMcpTemplateSyncConflictDescriptor))]
[JsonSerializable(typeof(EventMcpSummaryDescriptor))]
[JsonSerializable(typeof(EventMcpEventResultDescriptor))]
[JsonSerializable(typeof(EventMcpDetailDescriptor))]
[JsonSerializable(typeof(EventMcpProgramResultDescriptor))]
[JsonSerializable(typeof(EventMcpProgramSummaryDescriptor))]
[JsonSerializable(typeof(EventMcpProgramSectionDescriptor))]
[JsonSerializable(typeof(EventMcpProgramSessionGroupDescriptor))]
[JsonSerializable(typeof(EventMcpProgramDayDescriptor))]
[JsonSerializable(typeof(EventMcpProgramItemDescriptor))]
[JsonSerializable(typeof(EventMcpReadinessWarningDescriptor))]
[JsonSerializable(typeof(EventMcpSessionListResultDescriptor))]
[JsonSerializable(typeof(EventMcpSessionSummaryDescriptor))]
public sealed partial class EventManagementMcpJsonContext : JsonSerializerContext;
