// ABOUTME: Base interface for module-specific event business logic.
// Enables modular business logic that adapts at runtime based on tenant capabilities.

using Explore.Application.DTOs.Event;
using Explore.Domain;
using FluentValidation.Results;

namespace Explore.Application.Contracts.Strategies;

/// <summary>
/// Base interface for module-specific event business logic.
/// Strategies are resolved based on tenant capabilities and DTO content.
/// </summary>
public interface IEventStrategy
{
    /// <summary>
    /// Module key this strategy applies to (e.g., "Mod_Islamic", "Mod_Tech").
    /// </summary>
    string ModuleKey { get; }

    /// <summary>
    /// Priority for strategy execution order (lower = higher priority).
    /// </summary>
    int Priority => 100;

    /// <summary>
    /// Validates module-specific fields in the DTO.
    /// Called during command validation.
    /// </summary>
    /// <param name="dto">The event DTO being validated.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Validation result with any errors.</returns>
    Task<ValidationResult> ValidateAsync(CreateEventRequest request, CancellationToken cancellationToken = default);

    /// <summary>
    /// Applies module-specific business logic after event creation.
    /// Called in the command handler after the event is saved.
    /// </summary>
    /// <param name="event">The created event entity.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task PostCreateAsync(Event @event, CancellationToken cancellationToken = default);

    /// <summary>
    /// Applies module-specific business logic after event update.
    /// Called in the command handler after the event is updated.
    /// </summary>
    /// <param name="event">The updated event entity.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task PostUpdateAsync(Event @event, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets module-specific HATEOAS links for the event.
    /// </summary>
    /// <param name="event">The event to generate links for.</param>
    /// <returns>Collection of link DTOs.</returns>
    IEnumerable<StrategyLink> GetLinks(Event @event);

    /// <summary>
    /// Checks if this strategy is applicable to the given DTO.
    /// </summary>
    /// <param name="dto">The DTO to check.</param>
    /// <returns>True if this strategy should be applied.</returns>
    bool IsApplicable(CreateEventRequest request);
}

/// <summary>
/// Represents a link generated by a strategy.
/// </summary>
public class StrategyLink
{
    /// <summary>
    /// Link relation type (e.g., "islamic-details", "tech-details").
    /// </summary>
    public string Rel { get; init; } = string.Empty;

    /// <summary>
    /// URL for the link.
    /// </summary>
    public string Href { get; init; } = string.Empty;

    /// <summary>
    /// HTTP method for the link.
    /// </summary>
    public string Method { get; init; } = "GET";

    /// <summary>
    /// Human-readable title for the link.
    /// </summary>
    public string? Title { get; init; }
}
