<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Explore.Domain\Explore.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\AudienceAge\Validators\" />
    <Folder Include="DTOs\AudienceGender\Validators\" />
    <Folder Include="DTOs\EducationType\Validators\" />
    <Folder Include="DTOs\Education\Validators\" />
    <Folder Include="DTOs\EventType\Validators\" />
    <Folder Include="DTOs\ProgramRegistration\" />
    <Folder Include="DTOs\OrganizationMember\Validators\" />
    <Folder Include="DTOs\Organization\Validators\" />
    <Folder Include="DTOs\ProgramType\Validators\" />
    <Folder Include="DTOs\Program\Validators\" />
    <Folder Include="DTOs\StatusType\Validators\" />
    <Folder Include="Features\AudienceGenders\Handlers\Commands\" />
    <Folder Include="Features\AudienceGenders\Requests\Commands\" />
    <Folder Include="Features\Educations\Requests\Commands\" />
  </ItemGroup>

</Project>
