// ABOUTME: Guardrail tests for generated NSwag tag client contracts and DTOs.
// ABOUTME: Asserts operation-id-derived method names are stable, unique, and free of NSwag collision fallbacks.

using System.Reflection;
using System.Text.RegularExpressions;
using Explore.Blazor.Client.Clients;
using Explore.Blazor.Client.Extensions;

namespace Explore.Blazor.Client.Tests;

/// <summary>
/// Guardrail tests that enforce the ergonomics bar on generated tag clients.
///
/// These tests protect
/// the stabilized API OpenAPI surface from regressing back to duplicate URL-segment aliases or
/// unstable operation IDs that force NSwag collision-disambiguation suffixes such as
/// <c>Foo2Async</c>, <c>Foo3Async</c>, or <c>TenantGET2Async</c>.
///
/// Strategy: reflect over generated tag client interfaces, collect every async
/// method name, and assert against the naming invariants defined in the plan.
/// </summary>
public class ApiClientNamingTests
{
    private static readonly string[] RequiredSchedulingDtoTypeNames =
    [
        "EventAgendaItemDto",
        "EventAgendaItemListDto",
        "EventDayDto",
        "EventDayListDto",
        "LocationRoomDto",
        "LocationRoomListDto"
    ];

    private static readonly string[] RequiredSchedulingHalWrapperTypeNames =
    [
        "HalResourceOfEventAgendaItemDto",
        "HalResourceOfEventDayDto",
        "HalResourceOfLocationRoomDto",
        "HalCollectionResourceOfEventAgendaItemListDto",
        "HalCollectionResourceOfEventDayListDto",
        "HalCollectionResourceOfLocationRoomListDto"
    ];

    private static readonly string[] RequiredTenantSettingsMethodNames =
    [
        "PatchTenantStorageSettingsAsync",
        "PatchTenantBrandingSettingsDocumentAsync",
        "PatchTenantFooterSettingsAsync",
        "GetTenantFooterSettingsAsync"
    ];

    private static readonly string[] StableRegistrationProviderUntypedHalCollections =
    [
        "HalCollectionEmbeddedOfRegistrationChannelDto",
        "HalCollectionEmbeddedOfRegistrationProviderBindingDto",
        "HalCollectionEmbeddedOfRegistrationProviderBindingHealthDto",
        "HalCollectionEmbeddedOfRegistrationProviderConnectionDto",
        "HalCollectionEmbeddedOfRegistrationProviderParkedQueueItemDto"
    ];

    private static readonly string[] LegacyTenantSettingsMethodNames =
    [
        "UpdateTenantStorageSettingsAsync",
        "ReplaceTenantBrandingSettingsDocumentAsync",
        "UpdateTenantFooterSettingsAsync"
    ];

    /// <summary>
    /// Exact-match banned method names. These are NSwag's collision-disambiguation fallbacks
    /// observed in the current generated client. Phase 2+3 must eliminate every one of them.
    /// </summary>
    private static readonly string[] BannedExactMethodNames =
    [
        "GETAsync", "GET2Async", "GET3Async",
        "POSTAsync", "POST2Async", "POST3Async",
        "PUTAsync", "PUT2Async", "PUT3Async",
        "DELETEAsync", "DELETE2Async", "DELETE3Async",
        "PATCHAsync", "PATCH2Async", "PATCH3Async",
    ];

    /// <summary>
    /// Regex matching NSwag's suffix-disambiguation pattern: any method name whose name ends
    /// with one-or-more digits immediately before the <c>Async</c> suffix (e.g. <c>TenantGET2Async</c>,
    /// <c>AuthProviderGET2Async</c>, <c>Status8Async</c>).
    /// </summary>
    private static readonly Regex DigitBeforeAsyncSuffix = new(@"\d+Async$", RegexOptions.Compiled);

    /// <summary>
    /// Regex matching a clean, stable operation-id-derived name. Phase 3 target shape.
    /// </summary>
    private static readonly Regex CleanAsyncMethodName =
        new(@"^[A-Z][A-Za-z0-9]+Async$", RegexOptions.Compiled);

    private static readonly Regex GeneratedAnonymousClassName =
        new(@"public partial (?:record )?class Anonymous\d+", RegexOptions.Compiled);

    [Test]
    public async Task GeneratedTagClients_AreDiscoverable()
    {
        var clientTypes = GeneratedEventApiClients.ClientTypes;

        await Assert.That(clientTypes).IsNotEmpty()
            .Because("Reflection target GeneratedEventApiClients.ClientTypes must resolve from the Explore.Blazor.Client assembly.");
        await Assert.That(clientTypes.Count).IsEqualTo(162)
            .Because("Generated client registry should reflect all 162 OpenAPI tag client pairs.");

        foreach (var pair in clientTypes)
        {
            await Assert.That(pair.InterfaceType.IsInterface).IsTrue()
                .Because($"{pair.InterfaceType.Name} is expected to be a public interface generated by NSwag.");
            await Assert.That(pair.ImplementationType.IsClass).IsTrue()
                .Because($"{pair.ImplementationType.Name} is expected to be a public class generated by NSwag.");
        }
    }

    [Test]
    public async Task GeneratedTagClients_HaveAtLeastOneAsyncMethod()
    {
        var asyncMethods = GetAsyncMethodNames();

        await Assert.That(asyncMethods.Count > 0).IsTrue()
            .Because("Generated client should expose at least one *Async method; zero methods indicates a generation failure.");
    }

    [Test]
    public async Task GeneratedTagClients_NoMethodUsesCollisionSuffixPattern()
    {
        var offenders = GetAsyncMethodNames()
            .Where(name => DigitBeforeAsyncSuffix.IsMatch(name))
            .OrderBy(name => name)
            .ToList();

        await Assert.That(offenders).IsEmpty()
            .Because(
                $"Every method on generated tag clients ending in '\\dAsync' is a NSwag collision fallback " +
                $"and indicates duplicate or unstable OpenAPI operationIds. Offenders: {offenders.Count}. " +
                $"First 10: {string.Join(", ", offenders.Take(10))}.");
    }

    [Test]
    public async Task GeneratedTagClients_NoMethodUsesExactBannedPlaceholderName()
    {
        var asyncMethods = GetAsyncMethodNames().ToHashSet(StringComparer.Ordinal);
        var offenders = BannedExactMethodNames
            .Where(name => asyncMethods.Contains(name))
            .OrderBy(name => name)
            .ToList();

        await Assert.That(offenders).IsEmpty()
            .Because(
                $"Generated methods whose names equal a raw HTTP verb (with optional digit suffix) are " +
                $"always NSwag placeholders — they carry zero semantic information. Offenders: " +
                $"[{string.Join(", ", offenders)}].");
    }

    [Test]
    public async Task GeneratedTagClients_AllMethodNamesMatchCleanOperationIdShape()
    {
        var offenders = GetAsyncMethodNames()
            .Where(name => !CleanAsyncMethodName.IsMatch(name))
            .OrderBy(name => name)
            .ToList();

        await Assert.That(offenders).IsEmpty()
            .Because(
                $"Post-stabilization, every generated tag client method name must match " +
                $"'^[A-Z][A-Za-z0-9]+Async$' — a clean PascalCase operationId followed by 'Async'. " +
                $"Offenders: {offenders.Count}. First 10: {string.Join(", ", offenders.Take(10))}.");
    }

    [Test]
    public async Task GeneratedTagClients_MethodNamesAreUniqueWithinInterface()
    {
        var duplicates = GeneratedEventApiClients.ClientTypes
            .SelectMany(pair => pair.InterfaceType
                .GetMethods(BindingFlags.Public | BindingFlags.Instance)
                .GroupBy(m => (Interface: pair.InterfaceType.Name, m.Name, Parameters: string.Join(",",
                    m.GetParameters().Select(p => p.ParameterType.FullName ?? p.ParameterType.Name))))
                .Where(g => g.Count() > 1)
                .Select(g => $"{g.Key.Interface}.{g.Key.Name}({g.Key.Parameters})"))
            .OrderBy(s => s)
            .ToList();

        await Assert.That(duplicates).IsEmpty()
            .Because($"Reflection found duplicate (name, signature) methods on generated tag client interfaces: [{string.Join("; ", duplicates)}].");
    }

    [Test]
    public async Task GeneratedClient_TenantSettingsMethodsUseCanonicalNamesWithoutCompatibilityOverloads()
    {
        var generatedClientSource = GetGeneratedClientSource();
        var generatedMethodNames = GetGeneratedAsyncMethodDeclarationNames(generatedClientSource);

        foreach (var requiredMethodName in RequiredTenantSettingsMethodNames)
        {
            await Assert.That(generatedMethodNames.Count(name => name == requiredMethodName))
                .IsEqualTo(2)
                .Because($"Generated source must contain exactly the interface and class declarations for {requiredMethodName}, without a compatibility overload.");
        }

        foreach (var legacyMethodName in LegacyTenantSettingsMethodNames)
        {
            await Assert.That(generatedMethodNames.Contains(legacyMethodName, StringComparer.Ordinal)).IsFalse();
            await Assert.That(generatedClientSource.Contains($"{legacyMethodName}(", StringComparison.Ordinal))
                .IsFalse()
                .Because($"Generated client source must not retain the retired {legacyMethodName} compatibility method.");
        }
    }

    [Test]
    public async Task GeneratedClient_EmitsSchedulingDtoTypes()
    {
        var generatedClientSource = GetGeneratedClientSource();
        var missing = RequiredSchedulingDtoTypeNames
            .Where(typeName => !generatedClientSource.Contains($"public partial record class {typeName}", StringComparison.Ordinal))
            .OrderBy(name => name)
            .ToList();

        await Assert.That(missing).IsEmpty()
            .Because("Scheduling contracts must be generated rather than hand-maintained in Blazor. "
                + $"Missing: [{string.Join(", ", missing)}].");
    }

    [Test]
    public async Task GeneratedClient_StillEmitsSchedulingHalWrapperTypes()
    {
        var generatedClientSource = GetGeneratedClientSource();
        var missing = RequiredSchedulingHalWrapperTypeNames
            .Where(typeName => !generatedClientSource.Contains($"public partial class {typeName}", StringComparison.Ordinal))
            .OrderBy(name => name)
            .ToList();

        await Assert.That(missing).IsEmpty()
            .Because("Scheduling DTOs and their HAL wrapper schemas must remain generated for API responses. "
                + $"Missing: [{string.Join(", ", missing)}].");
    }

    [Test]
    public async Task GeneratedClient_DoesNotEmitUntypedHalEmbeddedItemCollections()
    {
        var generatedClientSource = GetGeneratedClientSource();
        var offenders = GetUntypedHalEmbeddedCollectionTypeNames(generatedClientSource)
            .Except(StableRegistrationProviderUntypedHalCollections, StringComparer.Ordinal)
            .ToList();

        await Assert.That(offenders).IsEmpty()
            .Because("HAL embedded collection item arrays should stay typed so generated clients do not fall back to ICollection<object>. "
                + $"Actual offenders: [{string.Join(", ", offenders)}].");
    }

    [Test]
    public async Task GeneratedClient_DoesNotEmitAnonymousSchemaTypes()
    {
        var generatedClientSource = GetGeneratedClientSource();
        var offenders = GeneratedAnonymousClassName
            .Matches(generatedClientSource)
            .Select(match => match.Value["public partial class ".Length..])
            .Distinct(StringComparer.Ordinal)
            .OrderBy(name => name)
            .ToList();

        await Assert.That(offenders).IsEmpty()
            .Because("OpenAPI schemas should use named component references instead of inline object schemas that NSwag emits as AnonymousN classes. "
                + $"Actual offenders: [{string.Join(", ", offenders)}].");
    }

    [Test]
    public async Task GeneratedClientCarriesOwnedRecordTransformationStamp()
    {
        var generatedClientSource = GetGeneratedClientSource();

        await Assert.That(generatedClientSource)
            .Contains("// <generated-record-policy version=\"1\">");
        await Assert.That(generatedClientSource)
            .Contains("public partial record class ActorDto");
        await Assert.That(generatedClientSource)
            .Contains("public partial class PublicExperienceClient");
        await Assert.That(generatedClientSource)
            .Contains("public partial class HalResourceOfActorDto");
        await Assert.That(generatedClientSource)
            .Contains("public partial class PatchTenantFooterSettingsDto");
    }

    private static List<string> GetAsyncMethodNames() =>
        GeneratedEventApiClients.ClientTypes
            .SelectMany(pair => pair.InterfaceType.GetMethods(BindingFlags.Public | BindingFlags.Instance))
            .Where(m => m.Name.EndsWith("Async", StringComparison.Ordinal))
            .Select(m => m.Name)
            .Distinct(StringComparer.Ordinal)
            .ToList();

    private static string GetGeneratedClientSource()
    {
        var generatedClientPath = Path.GetFullPath(Path.Combine(
            AppContext.BaseDirectory,
            "../../../../../src/Explore.Blazor.Client/Clients/EventApiTagClients.g.cs"));

        return File.ReadAllText(generatedClientPath);
    }

    private static List<string> GetGeneratedAsyncMethodDeclarationNames(string generatedClientSource)
    {
        var methodNames = new List<string>();

        using var reader = new StringReader(generatedClientSource);
        string? line;
        while ((line = reader.ReadLine()) is not null)
        {
            var trimmed = line.TrimStart();
            if (!trimmed.StartsWith("System.Threading.Tasks.Task", StringComparison.Ordinal)
                && !trimmed.StartsWith("public virtual async System.Threading.Tasks.Task", StringComparison.Ordinal))
            {
                continue;
            }

            var openParenthesis = trimmed.IndexOf('(', StringComparison.Ordinal);
            var lastSpace = openParenthesis > 0
                ? trimmed.LastIndexOf(' ', openParenthesis - 1)
                : -1;
            if (lastSpace < 0)
            {
                continue;
            }

            var methodName = trimmed[(lastSpace + 1)..openParenthesis];
            if (methodName.EndsWith("Async", StringComparison.Ordinal))
            {
                methodNames.Add(methodName);
            }
        }

        return methodNames;
    }

    private static List<string> GetUntypedHalEmbeddedCollectionTypeNames(string generatedClientSource)
    {
        var offenders = new List<string>();
        string? currentType = null;

        using var reader = new StringReader(generatedClientSource);
        string? line;
        while ((line = reader.ReadLine()) is not null)
        {
            var trimmed = line.Trim();
            if (trimmed.StartsWith("public partial class ", StringComparison.Ordinal))
            {
                currentType = trimmed["public partial class ".Length..]
                    .Split(' ', StringSplitOptions.RemoveEmptyEntries)[0];
                continue;
            }

            if (currentType is not null
                && trimmed.Contains("public System.Collections.Generic.ICollection<object>? Items", StringComparison.Ordinal))
            {
                offenders.Add(currentType);
            }
        }

        return offenders
            .Distinct(StringComparer.Ordinal)
            .OrderBy(name => name)
            .ToList();
    }
}
