// ABOUTME: Extension methods for HAL resource types generated by NSwag to provide convenient accessors.
// Bridges the gap between NSwag-generated HAL wrapper types and the code that expects plain DTO collections.

using System.Text.Json;
using Explore.Blazor.Client.Clients;
using Explore.Blazor.Client.Models;
using Explore.Blazor.Client.Models.CustomProperties;
using Explore.Blazor.Client.Models.EventSessionGroups;
using Explore.Blazor.Client.Models.EventSessionTemplates;

namespace Explore.Blazor.Client.Helpers;

/// <summary>
/// Extension methods for HAL collection resources to provide typed Items accessors.
/// The NSwag-generated HAL types have Items as ICollection&lt;object&gt; due to OpenAPI schema limitations.
/// These extensions provide strongly-typed access by deserializing the objects to their proper types.
/// </summary>
public static class HalResourceExtensions
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull
    };

    // ========== Event Extensions ==========

    /// <summary>
    /// Gets the typed items from a HAL collection of EventListDto.
    /// </summary>
    public static ICollection<EventListDto> GetItems(this HalCollectionResourceOfEventListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<EventListDto>();

        return DeserializeItems<EventListDto>(collection._embedded.Items);
    }

    /// <summary>
    /// Converts HalResourceOfEventDto to EventDto using JSON serialization.
    /// This ensures all properties are correctly mapped regardless of changes in the DTO schema.
    /// </summary>
    public static EventDto ToDto(this HalResourceOfEventDto halResource)
    {
        // Use JSON serialization to copy all matching properties
        var json = JsonSerializer.Serialize(halResource, JsonOptions);
        return JsonSerializer.Deserialize<EventDto>(json, JsonOptions) ?? new EventDto();
    }

    // ========== EventSession Extensions ==========

    /// <summary>
    /// Gets the typed items from a HAL collection of EventSessionListDto.
    /// </summary>
    public static ICollection<EventSessionListDto> GetItems(this HalCollectionResourceOfEventSessionListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<EventSessionListDto>();

        return DeserializeItems<EventSessionListDto>(collection._embedded.Items);
    }

    /// <summary>
    /// Converts HalResourceOfEventSessionDto to EventSessionDto using JSON serialization.
    /// </summary>
    public static EventSessionDto ToDto(this HalResourceOfEventSessionDto halResource)
    {
        var json = JsonSerializer.Serialize(halResource, JsonOptions);
        return JsonSerializer.Deserialize<EventSessionDto>(json, JsonOptions) ?? new EventSessionDto();
    }

    // ========== EventSessionGroup Extensions ==========

    /// <summary>
    /// Gets typed event program section/track/devroom items from a HAL collection.
    /// </summary>
    public static ICollection<EventSessionGroupListModel> GetItems(this HalCollectionResourceOfEventSessionGroupListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<EventSessionGroupListModel>();

        return DeserializeItems<EventSessionGroupListModel>(collection._embedded.Items);
    }

    // ========== Category Extensions ==========

    /// <summary>
    /// Gets the typed items from a HAL collection of CategoryListDto.
    /// </summary>
    public static ICollection<CategoryListDto> GetItems(this HalCollectionResourceOfCategoryListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<CategoryListDto>();

        return DeserializeItems<CategoryListDto>(collection._embedded.Items);
    }

    /// <summary>
    /// Converts HalResourceOfCategoryDto to CategoryDto using JSON serialization.
    /// </summary>
    public static CategoryDto ToDto(this HalResourceOfCategoryDto halResource)
    {
        var json = JsonSerializer.Serialize(halResource, JsonOptions);
        return JsonSerializer.Deserialize<CategoryDto>(json, JsonOptions) ?? new CategoryDto();
    }

    // ========== Tag Extensions ==========

    /// <summary>
    /// Gets the typed items from a HAL collection of TagListDto.
    /// </summary>
    public static ICollection<TagListDto> GetItems(this HalCollectionResourceOfTagListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<TagListDto>();

        return DeserializeItems<TagListDto>(collection._embedded.Items);
    }

    /// <summary>
    /// Converts HalResourceOfTagDto to TagDto using JSON serialization.
    /// </summary>
    public static TagDto ToDto(this HalResourceOfTagDto halResource)
    {
        try
        {
            var json = JsonSerializer.Serialize(halResource, JsonOptions);
            return JsonSerializer.Deserialize<TagDto>(json, JsonOptions) ?? new TagDto();
        }
        catch (JsonException)
        {
            return new TagDto
            {
                Id = halResource.Id,
                FullName = halResource.FullName ?? string.Empty,
                MasterCode = halResource.MasterCode ?? string.Empty
            };
        }
    }

    // ========== Location Extensions ==========

    /// <summary>
    /// Gets the typed items from a HAL collection of LocationListDto.
    /// </summary>
    public static ICollection<LocationListDto> GetItems(this HalCollectionResourceOfLocationListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<LocationListDto>();

        return DeserializeItems<LocationListDto>(collection._embedded.Items);
    }

    /// <summary>
    /// Converts HalResourceOfLocationDto to LocationDto using JSON serialization.
    /// </summary>
    public static LocationDto ToDto(this HalResourceOfLocationDto halResource)
    {
        var json = JsonSerializer.Serialize(halResource, JsonOptions);
        return JsonSerializer.Deserialize<LocationDto>(json, JsonOptions) ?? new LocationDto();
    }

    // ========== Organization Extensions ==========

    /// <summary>
    /// Gets the typed items from a HAL collection of OrganizationListDto.
    /// </summary>
    public static ICollection<OrganizationListDto> GetItems(this HalCollectionResourceOfOrganizationListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<OrganizationListDto>();

        return DeserializeItems<OrganizationListDto>(collection._embedded.Items);
    }

    /// <summary>
    /// Converts HalResourceOfOrganizationDto to OrganizationDto using JSON serialization.
    /// </summary>
    public static OrganizationDto ToDto(this HalResourceOfOrganizationDto halResource)
    {
        var json = JsonSerializer.Serialize(halResource, JsonOptions);
        return JsonSerializer.Deserialize<OrganizationDto>(json, JsonOptions) ?? new OrganizationDto();
    }

    // ========== Actor Extensions ==========

    /// <summary>
    /// Gets the typed items from a HAL collection of ActorListDto.
    /// </summary>
    public static ICollection<ActorListDto> GetItems(this HalCollectionResourceOfActorListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<ActorListDto>();

        return DeserializeItems<ActorListDto>(collection._embedded.Items);
    }

    /// <summary>
    /// Converts HalResourceOfActorDto to ActorDto using JSON serialization.
    /// </summary>
    public static ActorDto ToDto(this HalResourceOfActorDto halResource)
    {
        var json = JsonSerializer.Serialize(halResource, JsonOptions);
        return JsonSerializer.Deserialize<ActorDto>(json, JsonOptions) ?? new ActorDto();
    }

    // ========== LINQ-like Extensions for HAL Collections ==========

    /// <summary>
    /// Checks if the HAL collection contains any items.
    /// </summary>
    public static bool Any(this HalCollectionResourceOfEventListDto collection)
        => collection._embedded?.Items?.Count > 0;

    public static bool Any(this HalCollectionResourceOfEventSessionListDto collection)
        => collection._embedded?.Items?.Count > 0;

    public static bool Any(this HalCollectionResourceOfCategoryListDto collection)
        => collection._embedded?.Items?.Count > 0;

    public static bool Any(this HalCollectionResourceOfTagListDto collection)
        => collection._embedded?.Items?.Count > 0;

    public static bool Any(this HalCollectionResourceOfLocationListDto collection)
        => collection._embedded?.Items?.Count > 0;

    public static bool Any(this HalCollectionResourceOfOrganizationListDto collection)
        => collection._embedded?.Items?.Count > 0;

    public static bool Any(this HalCollectionResourceOfActorListDto collection)
        => collection._embedded?.Items?.Count > 0;

    /// <summary>
    /// Gets the count of items in the HAL collection.
    /// </summary>
    public static int Count(this HalCollectionResourceOfEventListDto collection)
        => collection._embedded?.Items?.Count ?? 0;

    public static int Count(this HalCollectionResourceOfEventSessionListDto collection)
        => collection._embedded?.Items?.Count ?? 0;

    public static int Count(this HalCollectionResourceOfCategoryListDto collection)
        => collection._embedded?.Items?.Count ?? 0;

    public static int Count(this HalCollectionResourceOfTagListDto collection)
        => collection._embedded?.Items?.Count ?? 0;

    public static int Count(this HalCollectionResourceOfLocationListDto collection)
        => collection._embedded?.Items?.Count ?? 0;

    public static int Count(this HalCollectionResourceOfOrganizationListDto collection)
        => collection._embedded?.Items?.Count ?? 0;

    public static int Count(this HalCollectionResourceOfActorListDto collection)
        => collection._embedded?.Items?.Count ?? 0;

    /// <summary>
    /// Converts HAL collection to a List for LINQ operations.
    /// </summary>
    public static List<EventListDto> ToList(this HalCollectionResourceOfEventListDto collection)
        => collection.GetItems().ToList();

    public static List<EventSessionListDto> ToList(this HalCollectionResourceOfEventSessionListDto collection)
        => collection.GetItems().ToList();

    public static List<CategoryListDto> ToList(this HalCollectionResourceOfCategoryListDto collection)
        => collection.GetItems().ToList();

    public static List<TagListDto> ToList(this HalCollectionResourceOfTagListDto collection)
        => collection.GetItems().ToList();

    public static List<LocationListDto> ToList(this HalCollectionResourceOfLocationListDto collection)
        => collection.GetItems().ToList();

    public static List<OrganizationListDto> ToList(this HalCollectionResourceOfOrganizationListDto collection)
        => collection.GetItems().ToList();

    public static List<ActorListDto> ToList(this HalCollectionResourceOfActorListDto collection)
        => collection.GetItems().ToList();

    /// <summary>
    /// Gets the first item or default from a HAL collection.
    /// </summary>
    public static EventListDto? FirstOrDefault(this HalCollectionResourceOfEventListDto collection)
        => collection.GetItems().FirstOrDefault();

    public static EventSessionListDto? FirstOrDefault(this HalCollectionResourceOfEventSessionListDto collection)
        => collection.GetItems().FirstOrDefault();

    public static CategoryListDto? FirstOrDefault(this HalCollectionResourceOfCategoryListDto collection)
        => collection.GetItems().FirstOrDefault();

    public static TagListDto? FirstOrDefault(this HalCollectionResourceOfTagListDto collection)
        => collection.GetItems().FirstOrDefault();

    public static LocationListDto? FirstOrDefault(this HalCollectionResourceOfLocationListDto collection)
        => collection.GetItems().FirstOrDefault();

    public static OrganizationListDto? FirstOrDefault(this HalCollectionResourceOfOrganizationListDto collection)
        => collection.GetItems().FirstOrDefault();

    public static ActorListDto? FirstOrDefault(this HalCollectionResourceOfActorListDto collection)
        => collection.GetItems().FirstOrDefault();

    /// <summary>
    /// Orders HAL collection items by a key selector.
    /// </summary>
    public static IOrderedEnumerable<EventSessionListDto> OrderBy<TKey>(
        this HalCollectionResourceOfEventSessionListDto collection,
        Func<EventSessionListDto, TKey> keySelector)
        => collection.GetItems().OrderBy(keySelector);

    /// <summary>
    /// Selects a projection from HAL collection items.
    /// </summary>
    public static IEnumerable<TResult> Select<TResult>(
        this HalCollectionResourceOfEventSessionListDto collection,
        Func<EventSessionListDto, TResult> selector)
        => collection.GetItems().Select(selector);

    // ========== Paginated Result Mappers ==========

    /// <summary>
    /// Maps a HAL collection response to a <see cref="PaginatedResult{T}"/> for Event lists.
    /// </summary>
    public static PaginatedResult<EventListDto> ToPaginatedResult(this HalCollectionResourceOfEventListDto? collection)
    {
        if (collection is null)
            return PaginatedResult<EventListDto>.Empty();

        return new PaginatedResult<EventListDto>
        {
            Items = collection.GetItems().ToList(),
            PageNumber = collection.PageNumber ?? 1,
            PageSize = collection.PageSize ?? 20,
            TotalCount = collection.TotalCount ?? 0
        };
    }

    /// <summary>
    /// Maps a HAL collection response to a <see cref="PaginatedResult{T}"/> for EventSession lists.
    /// </summary>
    public static PaginatedResult<EventSessionListDto> ToPaginatedResult(this HalCollectionResourceOfEventSessionListDto? collection)
    {
        if (collection is null)
            return PaginatedResult<EventSessionListDto>.Empty();

        return new PaginatedResult<EventSessionListDto>
        {
            Items = collection.GetItems().ToList(),
            PageNumber = collection.PageNumber ?? 1,
            PageSize = collection.PageSize ?? 20,
            TotalCount = collection.TotalCount ?? 0
        };
    }

    /// <summary>
    /// Maps a HAL collection response to a <see cref="PaginatedResult{T}"/> for Category lists.
    /// </summary>
    public static PaginatedResult<CategoryListDto> ToPaginatedResult(this HalCollectionResourceOfCategoryListDto? collection)
    {
        if (collection is null)
            return PaginatedResult<CategoryListDto>.Empty();

        return new PaginatedResult<CategoryListDto>
        {
            Items = collection.GetItems().ToList(),
            PageNumber = collection.PageNumber ?? 1,
            PageSize = collection.PageSize ?? 20,
            TotalCount = collection.TotalCount ?? 0
        };
    }

    /// <summary>
    /// Maps a HAL collection response to a <see cref="PaginatedResult{T}"/> for Tag lists.
    /// </summary>
    public static PaginatedResult<TagListDto> ToPaginatedResult(this HalCollectionResourceOfTagListDto? collection)
    {
        if (collection is null)
            return PaginatedResult<TagListDto>.Empty();

        return new PaginatedResult<TagListDto>
        {
            Items = collection.GetItems().ToList(),
            PageNumber = collection.PageNumber ?? 1,
            PageSize = collection.PageSize ?? 20,
            TotalCount = collection.TotalCount ?? 0
        };
    }

    /// <summary>
    /// Maps a HAL collection response to a <see cref="PaginatedResult{T}"/> for Location lists.
    /// </summary>
    public static PaginatedResult<LocationListDto> ToPaginatedResult(this HalCollectionResourceOfLocationListDto? collection)
    {
        if (collection is null)
            return PaginatedResult<LocationListDto>.Empty();

        return new PaginatedResult<LocationListDto>
        {
            Items = collection.GetItems().ToList(),
            PageNumber = collection.PageNumber ?? 1,
            PageSize = collection.PageSize ?? 20,
            TotalCount = collection.TotalCount ?? 0
        };
    }

    /// <summary>
    /// Maps a HAL collection response to a <see cref="PaginatedResult{T}"/> for Organization lists.
    /// </summary>
    public static PaginatedResult<OrganizationListDto> ToPaginatedResult(this HalCollectionResourceOfOrganizationListDto? collection)
    {
        if (collection is null)
            return PaginatedResult<OrganizationListDto>.Empty();

        return new PaginatedResult<OrganizationListDto>
        {
            Items = collection.GetItems().ToList(),
            PageNumber = collection.PageNumber ?? 1,
            PageSize = collection.PageSize ?? 20,
            TotalCount = collection.TotalCount ?? 0
        };
    }

    /// <summary>
    /// Maps a HAL collection response to a <see cref="PaginatedResult{T}"/> for Actor lists.
    /// </summary>
    public static PaginatedResult<ActorListDto> ToPaginatedResult(this HalCollectionResourceOfActorListDto? collection)
    {
        if (collection is null)
            return PaginatedResult<ActorListDto>.Empty();

        return new PaginatedResult<ActorListDto>
        {
            Items = collection.GetItems().ToList(),
            PageNumber = collection.PageNumber ?? 1,
            PageSize = collection.PageSize ?? 20,
            TotalCount = collection.TotalCount ?? 0
        };
    }

    // ========== EventDay Extensions ==========

    public static ICollection<EventDayListDto> GetItems(this HalCollectionResourceOfEventDayListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<EventDayListDto>();

        return DeserializeItems<EventDayListDto>(collection._embedded.Items);
    }

    public static EventDayDto ToDto(this HalResourceOfEventDayDto halResource)
    {
        var json = JsonSerializer.Serialize(halResource, JsonOptions);
        return JsonSerializer.Deserialize<EventDayDto>(json, JsonOptions) ?? new EventDayDto();
    }

    // ========== EventAgendaItem Extensions ==========

    public static ICollection<EventAgendaItemListDto> GetItems(this HalCollectionResourceOfEventAgendaItemListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<EventAgendaItemListDto>();

        return DeserializeItems<EventAgendaItemListDto>(collection._embedded.Items);
    }

    public static EventAgendaItemDto ToDto(this HalResourceOfEventAgendaItemDto halResource)
    {
        var json = JsonSerializer.Serialize(halResource, JsonOptions);
        return JsonSerializer.Deserialize<EventAgendaItemDto>(json, JsonOptions) ?? new EventAgendaItemDto();
    }

    // ========== LocationRoom Extensions ==========

    public static ICollection<LocationRoomListDto> GetItems(this HalCollectionResourceOfLocationRoomListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<LocationRoomListDto>();

        return DeserializeItems<LocationRoomListDto>(collection._embedded.Items);
    }

    public static LocationRoomDto ToDto(this HalResourceOfLocationRoomDto halResource)
    {
        var json = JsonSerializer.Serialize(halResource, JsonOptions);
        return JsonSerializer.Deserialize<LocationRoomDto>(json, JsonOptions) ?? new LocationRoomDto();
    }

    // ========== EventTemplate Extensions ==========

    public static ICollection<Explore.Blazor.Client.Models.EventTemplates.EventTemplateListModel> GetEventTemplateItems(this HalCollectionResourceOfEventTemplateListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<Explore.Blazor.Client.Models.EventTemplates.EventTemplateListModel>();

        return DeserializeItems<Explore.Blazor.Client.Models.EventTemplates.EventTemplateListModel>(collection._embedded.Items);
    }

    public static PaginatedResult<Explore.Blazor.Client.Models.EventTemplates.EventTemplateListModel> ToEventTemplatePaginatedResult(this HalCollectionResourceOfEventTemplateListDto? collection)
    {
        if (collection is null)
            return PaginatedResult<Explore.Blazor.Client.Models.EventTemplates.EventTemplateListModel>.Empty();

        return new PaginatedResult<Explore.Blazor.Client.Models.EventTemplates.EventTemplateListModel>
        {
            Items = collection.GetEventTemplateItems().ToList(),
            PageNumber = collection.PageNumber ?? 1,
            PageSize = collection.PageSize ?? 20,
            TotalCount = collection.TotalCount ?? 0
        };
    }

    public static Explore.Blazor.Client.Models.EventTemplates.EventTemplateDetailModel? ToEventTemplateModel(this HalResourceOfEventTemplateDto? halResource)
    {
        if (halResource is null)
            return null;

        var json = JsonSerializer.Serialize(halResource.AdditionalProperties, JsonOptions);
        return JsonSerializer.Deserialize<Explore.Blazor.Client.Models.EventTemplates.EventTemplateDetailModel>(json, JsonOptions);
    }

    // ========== EventSessionTemplate Extensions ==========

    public static ICollection<EventSessionTemplateListModel> GetEventSessionTemplateItems(this HalCollectionResourceOfEventSessionTemplateListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<EventSessionTemplateListModel>();

        return DeserializeItems<EventSessionTemplateListModel>(collection._embedded.Items);
    }

    public static PaginatedResult<EventSessionTemplateListModel> ToEventSessionTemplatePaginatedResult(this HalCollectionResourceOfEventSessionTemplateListDto? collection)
    {
        if (collection is null)
            return PaginatedResult<EventSessionTemplateListModel>.Empty();

        return new PaginatedResult<EventSessionTemplateListModel>
        {
            Items = collection.GetEventSessionTemplateItems().ToList(),
            PageNumber = collection.PageNumber ?? 1,
            PageSize = collection.PageSize ?? 20,
            TotalCount = collection.TotalCount ?? 0
        };
    }

    public static EventSessionTemplateDetailModel? ToEventSessionTemplateModel(this HalResourceOfEventSessionTemplateDto? halResource)
    {
        if (halResource is null)
            return null;

        var json = JsonSerializer.Serialize(halResource.AdditionalProperties, JsonOptions);
        return JsonSerializer.Deserialize<EventSessionTemplateDetailModel>(json, JsonOptions);
    }

    // ========== Custom Property Definition Extensions ==========

    public static ICollection<CustomPropertyDefinitionListModel> GetItems(this HalCollectionResourceOfCustomPropertyDefinitionListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<CustomPropertyDefinitionListModel>();

        return DeserializeItems<CustomPropertyDefinitionListModel>(collection._embedded.Items);
    }

    public static PaginatedResult<CustomPropertyDefinitionListModel> ToPaginatedResult(this HalCollectionResourceOfCustomPropertyDefinitionListDto? collection)
    {
        if (collection is null)
            return PaginatedResult<CustomPropertyDefinitionListModel>.Empty();

        return new PaginatedResult<CustomPropertyDefinitionListModel>
        {
            Items = collection.GetItems().ToList(),
            PageNumber = collection.PageNumber ?? 1,
            PageSize = collection.PageSize ?? 20,
            TotalCount = collection.TotalCount ?? 0
        };
    }

    public static ICollection<CustomPropertyDefinitionListModel> GetItems(this HalCollectionResourceOfEventCustomPropertyDefinitionListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<CustomPropertyDefinitionListModel>();

        return DeserializeItems<CustomPropertyDefinitionListModel>(collection._embedded.Items);
    }

    public static ICollection<CustomPropertyDefinitionListModel> GetItems(this HalCollectionResourceOfEventSessionCustomPropertyDefinitionListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<CustomPropertyDefinitionListModel>();

        return DeserializeItems<CustomPropertyDefinitionListModel>(collection._embedded.Items);
    }

    public static CustomPropertyDefinitionDetailModel? ToModel(this HalResourceOfCustomPropertyDefinitionDto? halResource)
    {
        if (halResource is null)
            return null;

        var json = JsonSerializer.Serialize(halResource.AdditionalProperties, JsonOptions);
        return JsonSerializer.Deserialize<CustomPropertyDefinitionDetailModel>(json, JsonOptions);
    }

    public static CustomPropertyDefinitionDetailModel? ToModel(this HalResourceOfEventCustomPropertyDefinitionDto? halResource)
    {
        if (halResource is null)
            return null;

        var json = JsonSerializer.Serialize(halResource.AdditionalProperties, JsonOptions);
        return JsonSerializer.Deserialize<CustomPropertyDefinitionDetailModel>(json, JsonOptions);
    }

    public static CustomPropertyDefinitionDetailModel? ToModel(this HalResourceOfEventSessionCustomPropertyDefinitionDto? halResource)
    {
        if (halResource is null)
            return null;

        var json = JsonSerializer.Serialize(halResource.AdditionalProperties, JsonOptions);
        return JsonSerializer.Deserialize<CustomPropertyDefinitionDetailModel>(json, JsonOptions);
    }

    // ========== Non-HAL Paginated Result Mappers ==========

    /// <summary>
    /// Maps a NSwag-generated <see cref="PaginatedResultOfEventRegistrationListDto"/> to a <see cref="PaginatedResult{T}"/>.
    /// Unlike HAL collections, registrations use a plain PaginatedResult response from the API.
    /// </summary>
    public static PaginatedResult<EventRegistrationListDto> ToPaginatedResult(this PaginatedResultOfEventRegistrationListDto? result)
    {
        if (result is null)
            return PaginatedResult<EventRegistrationListDto>.Empty();

        return new PaginatedResult<EventRegistrationListDto>
        {
            Items = result.Items?.ToList() ?? [],
            PageNumber = result.PageNumber ?? 1,
            PageSize = result.PageSize ?? 20,
            TotalCount = result.TotalCount ?? 0
        };
    }

    // ========== HAL Link Helpers ==========

    public static bool HasHalLink(this EventListDto dto, string linkRel)
        => HasHalLinkInAdditionalProperties(dto.AdditionalProperties, linkRel);

    public static bool HasManagementLinks(this EventListDto dto)
        => dto.HasHalLink("edit") || dto.HasHalLink("delete");

    public static bool HasLink(this HalResourceOfEventDto dto, string linkRel)
        => dto._links?.ContainsKey(linkRel) == true;

    public static bool HasHalLink(this EventDto dto, string linkRel)
        => HasHalLinkInAdditionalProperties(dto.AdditionalProperties, linkRel);

    public static bool HasHalLink(this EventSessionDto dto, string linkRel)
        => HasHalLinkInAdditionalProperties(dto.AdditionalProperties, linkRel);

    public static bool HasHalLink(this EventSessionGroupListModel dto, string linkRel)
        => HasHalLinkInAdditionalProperties(dto.AdditionalProperties, linkRel);

    // ========== Organization HAL Link Helpers ==========

    public static bool HasHalLink(this OrganizationDto dto, string linkRel)
        => HasHalLinkInAdditionalProperties(dto.AdditionalProperties, linkRel);

    public static bool HasHalLink(this OrganizationListDto dto, string linkRel)
        => HasHalLinkInAdditionalProperties(dto.AdditionalProperties, linkRel);

    public static bool HasManagementLinks(this OrganizationListDto dto)
        => dto.HasHalLink("edit") || dto.HasHalLink("delete");

    public static bool HasLink(this HalResourceOfOrganizationDto dto, string linkRel)
        => dto._links?.ContainsKey(linkRel) == true;

    // ========== Group HAL Link Helpers ==========

    public static bool HasLink(this HalResourceOfGroupDto dto, string linkRel)
        => HasHalLinkInAdditionalProperties(dto.AdditionalProperties, linkRel);

    public static bool HasManagementLinks(this HalResourceOfGroupDto dto)
        => dto.HasLink("edit") || dto.HasLink("delete");

    // ========== Helper Methods ==========

    private static bool HasHalLinkInAdditionalProperties(IDictionary<string, object>? additionalProperties, string linkRel)
    {
        if (additionalProperties == null ||
            !additionalProperties.TryGetValue("_links", out var linksObj))
            return false;

        if (linksObj is JsonElement linksElement && linksElement.ValueKind == JsonValueKind.Object)
            return linksElement.TryGetProperty(linkRel, out _);

        return false;
    }

    /// <summary>
    /// Deserializes a collection of objects to a strongly-typed collection.
    /// This handles the case where NSwag generates Items as ICollection&lt;object&gt;
    /// but the actual JSON contains properly typed objects.
    /// Supports System.Text.Json JsonElement from the NSwag SystemTextJson generator.
    /// </summary>
    private static ICollection<T> DeserializeItems<T>(ICollection<object> items) where T : class
    {
        var result = new List<T>(items.Count);
        foreach (var item in items)
        {
            if (item is T typedItem)
            {
                // Already the correct type - best case
                result.Add(typedItem);
            }
            else if (item is JsonElement jsonElement)
            {
                // System.Text.Json path (NSwag SystemTextJson generator)
                var deserialized = JsonSerializer.Deserialize<T>(
                    jsonElement.GetRawText(),
                    JsonOptions);
                if (deserialized != null)
                    result.Add(deserialized);
            }
            else
            {
                // Fallback: JSON serialization roundtrip for unknown types
                var json = JsonSerializer.Serialize(item, JsonOptions);
                var deserialized = JsonSerializer.Deserialize<T>(json, JsonOptions);
                if (deserialized != null)
                    result.Add(deserialized);
            }
        }
        return result;
    }
}
