// ABOUTME: Extension methods for HAL resource types generated by NSwag to provide convenient accessors.
// Bridges the gap between NSwag-generated HAL wrapper types and the code that expects plain DTO collections.

using Explore.Blazor.Client.Clients;
using Newtonsoft.Json;

namespace Explore.Blazor.Client.Helpers;

/// <summary>
/// Extension methods for HAL collection resources to provide typed Items accessors.
/// The NSwag-generated HAL types have Items as ICollection&lt;object&gt; due to OpenAPI schema limitations.
/// These extensions provide strongly-typed access by deserializing the objects to their proper types.
/// </summary>
public static class HalResourceExtensions
{
    private static readonly JsonSerializerSettings JsonSettings = new()
    {
        NullValueHandling = NullValueHandling.Ignore,
        MissingMemberHandling = MissingMemberHandling.Ignore
    };

    // ========== Event Extensions ==========

    /// <summary>
    /// Gets the typed items from a HAL collection of EventListDto.
    /// </summary>
    public static ICollection<EventListDto> GetItems(this HalCollectionResourceOfEventListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<EventListDto>();

        return DeserializeItems<EventListDto>(collection._embedded.Items);
    }

    /// <summary>
    /// Converts HalResourceOfEventDto to EventDto using JSON serialization.
    /// This ensures all properties are correctly mapped regardless of changes in the DTO schema.
    /// </summary>
    public static EventDto ToDto(this HalResourceOfEventDto halResource)
    {
        // Use JSON serialization to copy all matching properties
        var json = JsonConvert.SerializeObject(halResource, JsonSettings);
        return JsonConvert.DeserializeObject<EventDto>(json, JsonSettings) ?? new EventDto();
    }

    // ========== EventSession Extensions ==========

    /// <summary>
    /// Gets the typed items from a HAL collection of EventSessionListDto.
    /// </summary>
    public static ICollection<EventSessionListDto> GetItems(this HalCollectionResourceOfEventSessionListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<EventSessionListDto>();

        return DeserializeItems<EventSessionListDto>(collection._embedded.Items);
    }

    /// <summary>
    /// Converts HalResourceOfEventSessionDto to EventSessionDto using JSON serialization.
    /// </summary>
    public static EventSessionDto ToDto(this HalResourceOfEventSessionDto halResource)
    {
        var json = JsonConvert.SerializeObject(halResource, JsonSettings);
        return JsonConvert.DeserializeObject<EventSessionDto>(json, JsonSettings) ?? new EventSessionDto();
    }

    // ========== Category Extensions ==========

    /// <summary>
    /// Gets the typed items from a HAL collection of CategoryListDto.
    /// </summary>
    public static ICollection<CategoryListDto> GetItems(this HalCollectionResourceOfCategoryListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<CategoryListDto>();

        return DeserializeItems<CategoryListDto>(collection._embedded.Items);
    }

    /// <summary>
    /// Converts HalResourceOfCategoryDto to CategoryDto using JSON serialization.
    /// </summary>
    public static CategoryDto ToDto(this HalResourceOfCategoryDto halResource)
    {
        var json = JsonConvert.SerializeObject(halResource, JsonSettings);
        return JsonConvert.DeserializeObject<CategoryDto>(json, JsonSettings) ?? new CategoryDto();
    }

    // ========== Tag Extensions ==========

    /// <summary>
    /// Gets the typed items from a HAL collection of TagListDto.
    /// </summary>
    public static ICollection<TagListDto> GetItems(this HalCollectionResourceOfTagListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<TagListDto>();

        return DeserializeItems<TagListDto>(collection._embedded.Items);
    }

    /// <summary>
    /// Converts HalResourceOfTagDto to TagDto using JSON serialization.
    /// </summary>
    public static TagDto ToDto(this HalResourceOfTagDto halResource)
    {
        var json = JsonConvert.SerializeObject(halResource, JsonSettings);
        return JsonConvert.DeserializeObject<TagDto>(json, JsonSettings) ?? new TagDto();
    }

    // ========== Location Extensions ==========

    /// <summary>
    /// Gets the typed items from a HAL collection of LocationListDto.
    /// </summary>
    public static ICollection<LocationListDto> GetItems(this HalCollectionResourceOfLocationListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<LocationListDto>();

        return DeserializeItems<LocationListDto>(collection._embedded.Items);
    }

    /// <summary>
    /// Converts HalResourceOfLocationDto to LocationDto using JSON serialization.
    /// </summary>
    public static LocationDto ToDto(this HalResourceOfLocationDto halResource)
    {
        var json = JsonConvert.SerializeObject(halResource, JsonSettings);
        return JsonConvert.DeserializeObject<LocationDto>(json, JsonSettings) ?? new LocationDto();
    }

    // ========== Organization Extensions ==========

    /// <summary>
    /// Gets the typed items from a HAL collection of OrganizationListDto.
    /// </summary>
    public static ICollection<OrganizationListDto> GetItems(this HalCollectionResourceOfOrganizationListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<OrganizationListDto>();

        return DeserializeItems<OrganizationListDto>(collection._embedded.Items);
    }

    /// <summary>
    /// Converts HalResourceOfOrganizationDto to OrganizationDto using JSON serialization.
    /// </summary>
    public static OrganizationDto ToDto(this HalResourceOfOrganizationDto halResource)
    {
        var json = JsonConvert.SerializeObject(halResource, JsonSettings);
        return JsonConvert.DeserializeObject<OrganizationDto>(json, JsonSettings) ?? new OrganizationDto();
    }

    // ========== Actor Extensions ==========

    /// <summary>
    /// Gets the typed items from a HAL collection of ActorListDto.
    /// </summary>
    public static ICollection<ActorListDto> GetItems(this HalCollectionResourceOfActorListDto collection)
    {
        if (collection._embedded?.Items == null)
            return new List<ActorListDto>();

        return DeserializeItems<ActorListDto>(collection._embedded.Items);
    }

    /// <summary>
    /// Converts HalResourceOfActorDto to ActorDto using JSON serialization.
    /// </summary>
    public static ActorDto ToDto(this HalResourceOfActorDto halResource)
    {
        var json = JsonConvert.SerializeObject(halResource, JsonSettings);
        return JsonConvert.DeserializeObject<ActorDto>(json, JsonSettings) ?? new ActorDto();
    }

    // ========== LINQ-like Extensions for HAL Collections ==========

    /// <summary>
    /// Checks if the HAL collection contains any items.
    /// </summary>
    public static bool Any(this HalCollectionResourceOfEventListDto collection)
        => collection._embedded?.Items?.Count > 0;

    public static bool Any(this HalCollectionResourceOfEventSessionListDto collection)
        => collection._embedded?.Items?.Count > 0;

    public static bool Any(this HalCollectionResourceOfCategoryListDto collection)
        => collection._embedded?.Items?.Count > 0;

    public static bool Any(this HalCollectionResourceOfTagListDto collection)
        => collection._embedded?.Items?.Count > 0;

    public static bool Any(this HalCollectionResourceOfLocationListDto collection)
        => collection._embedded?.Items?.Count > 0;

    public static bool Any(this HalCollectionResourceOfOrganizationListDto collection)
        => collection._embedded?.Items?.Count > 0;

    public static bool Any(this HalCollectionResourceOfActorListDto collection)
        => collection._embedded?.Items?.Count > 0;

    /// <summary>
    /// Gets the count of items in the HAL collection.
    /// </summary>
    public static int Count(this HalCollectionResourceOfEventListDto collection)
        => collection._embedded?.Items?.Count ?? 0;

    public static int Count(this HalCollectionResourceOfEventSessionListDto collection)
        => collection._embedded?.Items?.Count ?? 0;

    public static int Count(this HalCollectionResourceOfCategoryListDto collection)
        => collection._embedded?.Items?.Count ?? 0;

    public static int Count(this HalCollectionResourceOfTagListDto collection)
        => collection._embedded?.Items?.Count ?? 0;

    public static int Count(this HalCollectionResourceOfLocationListDto collection)
        => collection._embedded?.Items?.Count ?? 0;

    public static int Count(this HalCollectionResourceOfOrganizationListDto collection)
        => collection._embedded?.Items?.Count ?? 0;

    public static int Count(this HalCollectionResourceOfActorListDto collection)
        => collection._embedded?.Items?.Count ?? 0;

    /// <summary>
    /// Converts HAL collection to a List for LINQ operations.
    /// </summary>
    public static List<EventListDto> ToList(this HalCollectionResourceOfEventListDto collection)
        => collection.GetItems().ToList();

    public static List<EventSessionListDto> ToList(this HalCollectionResourceOfEventSessionListDto collection)
        => collection.GetItems().ToList();

    public static List<CategoryListDto> ToList(this HalCollectionResourceOfCategoryListDto collection)
        => collection.GetItems().ToList();

    public static List<TagListDto> ToList(this HalCollectionResourceOfTagListDto collection)
        => collection.GetItems().ToList();

    public static List<LocationListDto> ToList(this HalCollectionResourceOfLocationListDto collection)
        => collection.GetItems().ToList();

    public static List<OrganizationListDto> ToList(this HalCollectionResourceOfOrganizationListDto collection)
        => collection.GetItems().ToList();

    public static List<ActorListDto> ToList(this HalCollectionResourceOfActorListDto collection)
        => collection.GetItems().ToList();

    /// <summary>
    /// Gets the first item or default from a HAL collection.
    /// </summary>
    public static EventListDto? FirstOrDefault(this HalCollectionResourceOfEventListDto collection)
        => collection.GetItems().FirstOrDefault();

    public static EventSessionListDto? FirstOrDefault(this HalCollectionResourceOfEventSessionListDto collection)
        => collection.GetItems().FirstOrDefault();

    public static CategoryListDto? FirstOrDefault(this HalCollectionResourceOfCategoryListDto collection)
        => collection.GetItems().FirstOrDefault();

    public static TagListDto? FirstOrDefault(this HalCollectionResourceOfTagListDto collection)
        => collection.GetItems().FirstOrDefault();

    public static LocationListDto? FirstOrDefault(this HalCollectionResourceOfLocationListDto collection)
        => collection.GetItems().FirstOrDefault();

    public static OrganizationListDto? FirstOrDefault(this HalCollectionResourceOfOrganizationListDto collection)
        => collection.GetItems().FirstOrDefault();

    public static ActorListDto? FirstOrDefault(this HalCollectionResourceOfActorListDto collection)
        => collection.GetItems().FirstOrDefault();

    /// <summary>
    /// Orders HAL collection items by a key selector.
    /// </summary>
    public static IOrderedEnumerable<EventSessionListDto> OrderBy<TKey>(
        this HalCollectionResourceOfEventSessionListDto collection,
        Func<EventSessionListDto, TKey> keySelector)
        => collection.GetItems().OrderBy(keySelector);

    /// <summary>
    /// Selects a projection from HAL collection items.
    /// </summary>
    public static IEnumerable<TResult> Select<TResult>(
        this HalCollectionResourceOfEventSessionListDto collection,
        Func<EventSessionListDto, TResult> selector)
        => collection.GetItems().Select(selector);

    // ========== Helper Methods ==========

    // System.Text.Json options for modern .NET compatibility
    private static readonly System.Text.Json.JsonSerializerOptions SystemTextJsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    /// <summary>
    /// Deserializes a collection of objects to a strongly-typed collection.
    /// This handles the case where NSwag generates Items as ICollection&lt;object&gt;
    /// but the actual JSON contains properly typed objects.
    /// Supports both Newtonsoft.Json (JObject) and System.Text.Json (JsonElement) for flexibility.
    /// </summary>
    private static ICollection<T> DeserializeItems<T>(ICollection<object> items) where T : class
    {
        var result = new List<T>(items.Count);
        foreach (var item in items)
        {
            if (item is T typedItem)
            {
                // Already the correct type - best case
                result.Add(typedItem);
            }
            else if (item is Newtonsoft.Json.Linq.JObject jObject)
            {
                // Newtonsoft.Json path (current NSwag config uses this)
                var deserialized = jObject.ToObject<T>();
                if (deserialized != null)
                    result.Add(deserialized);
            }
            else if (item is System.Text.Json.JsonElement jsonElement)
            {
                // System.Text.Json path (future-proofing if NSwag config changes)
                var deserialized = System.Text.Json.JsonSerializer.Deserialize<T>(
                    jsonElement.GetRawText(),
                    SystemTextJsonOptions);
                if (deserialized != null)
                    result.Add(deserialized);
            }
            else
            {
                // Fallback: JSON serialization roundtrip for unknown types
                var json = JsonConvert.SerializeObject(item, JsonSettings);
                var deserialized = JsonConvert.DeserializeObject<T>(json, JsonSettings);
                if (deserialized != null)
                    result.Add(deserialized);
            }
        }
        return result;
    }
}
