apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: default
  resource: tenant_setting
  rules:
    - actions:
        - update
      effect: EFFECT_ALLOW
      roles:
        - authenticated_user
      condition:
        match:
          expr: P.attr.isInstanceAdmin == true

    - actions:
        - update
      effect: EFFECT_ALLOW
      roles:
        - authenticated_user
      condition:
        match:
          expr: P.attr.tenantMemberships[R.attr.tenantId] == "admin" && R.attr.isLockedByInstance == false
