// ABOUTME: Typed, test-only governance inventory for durable User-linked personal-data copies.
// ABOUTME: Classifies local model fields and external copies without providing executable erasure instructions.

namespace Event.Architecture.Tests.Privacy;

internal enum UserPiiDisposition
{
    HardDelete,
    Anonymize,
    BoundedRetain,
    ExternalAction
}

internal enum UserPiiProviderAction
{
    None,
    DeletePlatformManagedIdentity,
    RevokeOrUnlinkExternalIdentity,
    DeleteOrAnonymizeProviderCopy,
    ExpireLocalMetadataWithoutRecall,
    InvalidateSubscription,
    DeleteOwnedObject,
    PurgeRetainedContext,
    CorrectOrDeleteProviderCopy
}

internal sealed record UserPiiInventoryEntry(
    string Copy,
    string OwnershipKey,
    string Producer,
    Type FenceOwner,
    UserPiiDisposition Disposition,
    string RetentionPurpose,
    string RetentionHorizon,
    UserPiiProviderAction ProviderAction,
    int PolicyVersion,
    IReadOnlyList<Type> ProviderSurfaces);

internal static class UserPiiInventory
{
    public const int CurrentPolicyVersion = 1;

    public static IReadOnlyList<UserPiiInventoryEntry> Entries { get; } =
    [
        Local("UserPii.Email", "UserPii.UserId", "SyncUserCommandHandler", UserPiiDisposition.HardDelete),
        Local("UserPii.FirstName", "UserPii.UserId", "SyncUserCommandHandler", UserPiiDisposition.HardDelete),
        Local("UserPii.LastName", "UserPii.UserId", "SyncUserCommandHandler", UserPiiDisposition.HardDelete),
        Local("ActorPii.DisplayName", "Actor.UserId -> ActorPii.ActorId", "Actor handlers", UserPiiDisposition.Anonymize,
            "Preserve shared authorship without identity", "Permanent anonymous tombstone"),
        Local("AtprotoIdentity.Did", "Actor.UserId -> AtprotoIdentity.ActorId", "ATProto actor synchronization", UserPiiDisposition.HardDelete),
        Local("AtprotoIdentity.Handle", "Actor.UserId -> AtprotoIdentity.ActorId", "ATProto actor synchronization", UserPiiDisposition.HardDelete),
        Local("ActorPii.ProfilePictureUri", "Actor.UserId -> ActorPii.ActorId", "Actor profile handlers", UserPiiDisposition.HardDelete),
        Local("LocationPii.Address", "Location.OwnerUserId -> LocationPii.LocationId", "Location handlers", UserPiiDisposition.HardDelete),
        Local("LocationPii.Postcode", "Location.OwnerUserId -> LocationPii.LocationId", "Location handlers", UserPiiDisposition.HardDelete),
        Local("TenantInvitation.Email", "TenantInvitation.InvitedByUserId or accepted UserId", "Tenant invitation handlers", UserPiiDisposition.HardDelete),
        Local("TenantInvitation.InvitedByUserId", "TenantInvitation.InvitedByUserId", "Tenant invitation handlers", UserPiiDisposition.Anonymize,
            "Invitation security audit", "Invitation expiry plus 30 days"),
        Local("TenantUser.UserId", "TenantUser.UserId", "Tenant membership handlers", UserPiiDisposition.HardDelete),
        Local("Event.SourcePublisherName", "Event provenance metadata; not subject-owned", "Event provenance import handlers", UserPiiDisposition.BoundedRetain,
            "Preserve source attribution for event provenance", "Event record lifecycle"),
        Local("Event.SubmittedByUserId", "Event.SubmittedByUserId", "CreateEventCommandHandler", UserPiiDisposition.Anonymize,
            "Preserve community-submitted event history without submitter identity", "Event record lifecycle"),
        Local("EventCapacityPool.Name", "EventCapacityPool.EventId; event-owned business data, not subject-owned", "Event ticket catalog handlers", UserPiiDisposition.BoundedRetain,
            "Preserve event capacity configuration", "Event record lifecycle"),
        Local("EventOrganizerClaim.ReviewerUserId", "EventOrganizerClaim.ReviewerUserId", "Event organizer claim review handlers", UserPiiDisposition.Anonymize,
            "Preserve organizer-claim decision evidence without reviewer identity", "Organizer-claim retention horizon"),
        Local("EventTicketType.Name", "EventTicketType.CatalogId; event-owned business data, not subject-owned", "Event ticket catalog handlers", UserPiiDisposition.BoundedRetain,
            "Preserve ticket catalog and order reconciliation", "Event record lifecycle"),
        Local("EventRegistration.LinkedUserId", "EventRegistration.LinkedUserId", "RegistrationOrderLifecycleService", UserPiiDisposition.HardDelete),
        Local("RegistrationOrder.AccountUserId", "RegistrationOrder.AccountUserId", "Registration order handlers", UserPiiDisposition.HardDelete),
        Local("RegistrationOrderLine.TicketTypeNameSnapshot", "RegistrationOrderLine.RegistrationOrderId -> RegistrationOrder.AccountUserId", "RegistrationOrderLine.Create", UserPiiDisposition.BoundedRetain,
            "Preserve the ticket display name for order history", "Configured registration-order retention horizon"),
        Local("RegistrationOrderPii.ContactName", "RegistrationOrder.AccountUserId -> RegistrationOrderPii.RegistrationOrderId", "Registration order handlers", UserPiiDisposition.HardDelete),
        Local("RegistrationOrderPii.Email", "RegistrationOrder.AccountUserId -> RegistrationOrderPii.RegistrationOrderId", "Registration order handlers", UserPiiDisposition.HardDelete),
        Local("RegistrationOrderPii.NormalizedEmail", "RegistrationOrder.AccountUserId -> RegistrationOrderPii.RegistrationOrderId", "Registration order handlers", UserPiiDisposition.HardDelete),
        Local("RegistrationOrderPii.Phone", "RegistrationOrder.AccountUserId -> RegistrationOrderPii.RegistrationOrderId", "Registration order handlers", UserPiiDisposition.HardDelete),
        Local("RegistrationOrderPii.OrganizationName", "RegistrationOrder.AccountUserId -> RegistrationOrderPii.RegistrationOrderId", "Registration order handlers", UserPiiDisposition.HardDelete),
        Local("RegistrationParticipant.LinkedUserId", "RegistrationParticipant.LinkedUserId", "RegistrationParticipantCommandService", UserPiiDisposition.Anonymize,
            "Preserve participant assignment and admission history without account linkage", "Permanent anonymous tombstone"),
        Local("RegistrationParticipantPii.DisplayName", "RegistrationParticipant.LinkedUserId -> RegistrationParticipantPii.RegistrationParticipantId", "RegistrationParticipantCommandService", UserPiiDisposition.HardDelete),
        Local("RegistrationParticipantPii.Email", "RegistrationParticipant.LinkedUserId -> RegistrationParticipantPii.RegistrationParticipantId", "RegistrationParticipantCommandService", UserPiiDisposition.HardDelete),
        Local("RegistrationParticipantPii.NormalizedEmail", "RegistrationParticipant.LinkedUserId -> RegistrationParticipantPii.RegistrationParticipantId", "RegistrationParticipantCommandService", UserPiiDisposition.HardDelete),
        Local("RegistrationParticipantPii.Phone", "RegistrationParticipant.LinkedUserId -> RegistrationParticipantPii.RegistrationParticipantId", "RegistrationParticipantCommandService", UserPiiDisposition.HardDelete),
        Local("EventContactShareConsent.EmailSnapshot", "EventContactShareConsent.UserId", "Contact-share consent handler", UserPiiDisposition.HardDelete),
        Local("EventContactShareConsent.EmailNormalizedSnapshot", "EventContactShareConsent.UserId", "Contact-share consent handler", UserPiiDisposition.HardDelete),
        Local("EventContactShareExport.ExportedByUserId", "EventContactShareExport.ExportedByUserId", "Contact-share export handler", UserPiiDisposition.Anonymize,
            "Export accountability", "Export retention horizon"),
        Local("EventContactShareExportItem.EmailSnapshot", "Export -> consent -> UserId", "Contact-share export handler", UserPiiDisposition.HardDelete),
        Local("Notification.UserId", "Notification.UserId", "RecipientNotificationMaterializer", UserPiiDisposition.HardDelete),
        Local("Notification.Title", "Notification.UserId", "RecipientNotificationMaterializer", UserPiiDisposition.HardDelete),
        Local("Notification.Body", "Notification.UserId", "RecipientNotificationMaterializer", UserPiiDisposition.HardDelete),
        Local("NotificationFanoutOccurrence.SafeBeforeSnapshotJson", "Fanout audience resolves UserId", "NotificationFanoutOccurrenceCoordinator", UserPiiDisposition.HardDelete),
        Local("NotificationFanoutOccurrence.SafeAfterSnapshotJson", "Fanout audience resolves UserId", "NotificationFanoutOccurrenceCoordinator", UserPiiDisposition.HardDelete),
        Local("NotificationIntent.SafePayloadReference", "NotificationIntent.RecipientUserId", "DefaultNotificationOrchestrator", UserPiiDisposition.HardDelete),
        Local("NotificationDelivery.ProviderMessageId", "NotificationIntent.RecipientUserId", "Notification delivery materializer", UserPiiDisposition.HardDelete),
        Local("NotificationExternalDelegation.ExternalProviderId", "Notification intent RecipientUserId", "External notification delegation worker", UserPiiDisposition.HardDelete),
        Local("EmailDispatchOutbox.RecipientEmail", "EmailDispatchOutbox.RecipientUserId", "EventLifecycleEmailOutboxFactory", UserPiiDisposition.HardDelete),
        Local("EmailDispatchOutbox.Subject", "EmailDispatchOutbox.RecipientUserId", "EventLifecycleEmailOutboxFactory", UserPiiDisposition.HardDelete),
        Local("EmailDispatchOutbox.HtmlBody", "EmailDispatchOutbox.UserId", "EventLifecycleEmailOutboxFactory", UserPiiDisposition.HardDelete),
        Local("EmailDispatchOutbox.PlainTextBody", "EmailDispatchOutbox.RecipientUserId", "EventLifecycleEmailOutboxFactory", UserPiiDisposition.HardDelete),
        Local("EmailDispatchAttempt.ProviderMessageId", "Attempt -> EmailDispatchOutbox.UserId", "EmailDispatchDrainService", UserPiiDisposition.BoundedRetain,
            "Delivery reconciliation and abuse handling", "Delivery record retention policy"),
        Local("EmailDispatchReceipt.ConsumerId", "Receipt -> EmailDispatchOutbox.UserId", "EmailDispatchDrainService", UserPiiDisposition.BoundedRetain,
            "Idempotent delivery settlement", "Delivery receipt retention policy"),
        Local("WebPushSubscription.Endpoint", "WebPushSubscription.UserId", "Web-push subscription handlers", UserPiiDisposition.HardDelete),
        Local("WebPushSubscription.P256Dh", "WebPushSubscription.UserId", "Web-push subscription handlers", UserPiiDisposition.HardDelete),
        Local("WebPushSubscription.AuthSecret", "WebPushSubscription.UserId", "Web-push subscription handlers", UserPiiDisposition.HardDelete),
        Local("WebPushDispatchOutbox.PayloadJson", "WebPushDispatchOutbox.UserId", "Web-push fanout", UserPiiDisposition.HardDelete),
        Local("IntegrationSyncOutbox.UserId", "IntegrationSyncOutbox.UserId", "ListmonkRegistrationSyncOutboxFactory", UserPiiDisposition.HardDelete),
        Local("IntegrationSyncOutbox.SubscriberEmail", "IntegrationSyncOutbox.UserId", "ListmonkRegistrationSyncOutboxFactory", UserPiiDisposition.HardDelete),
        Local("IntegrationSyncOutbox.SubscriberName", "IntegrationSyncOutbox.UserId", "ListmonkRegistrationSyncOutboxFactory", UserPiiDisposition.HardDelete),
        Local("IntegrationSyncOutbox.SubscriberPayloadJson", "IntegrationSyncOutbox.UserId", "ListmonkRegistrationSyncOutboxFactory", UserPiiDisposition.HardDelete),
        Local("AiConversation.UserId", "AiConversation.UserId", "AI conversation handlers", UserPiiDisposition.HardDelete),
        Local("AiMessage.Content", "Conversation -> AiConversation.UserId", "AI context gateway", UserPiiDisposition.HardDelete),
        Local("AiMessage.ImageAttachmentsJson", "Conversation -> AiConversation.UserId", "AI context gateway", UserPiiDisposition.HardDelete),
        Local("AiProposedAction.PayloadJson", "Conversation -> AiConversation.UserId", "AI tool orchestration", UserPiiDisposition.HardDelete),
        Local("AiToolExecution.FailureMessage", "Proposed action -> conversation -> UserId", "AI tool orchestration", UserPiiDisposition.HardDelete),
        Local("AiConversationReference.Summary", "Reference -> AiConversation.UserId", "AI context gateway", UserPiiDisposition.HardDelete),
        Local("WebhookMessage._payloadBytes", "Webhook aggregate ownership resolves UserId", "DefaultWebhookPayloadBuilder", UserPiiDisposition.HardDelete),
        Local("WebhookLocalTargetSnapshot.DestinationUrl", "Webhook consumer owner UserId", "Webhook delivery planner", UserPiiDisposition.HardDelete),
        Local("WebhookLocalTargetSnapshot.CredentialReference", "Webhook consumer owner UserId", "Webhook delivery planner", UserPiiDisposition.HardDelete),
        Local("WebhookProviderPublication.ProviderEventId", "Webhook consumer owner UserId", "Webhook provider publisher", UserPiiDisposition.BoundedRetain,
            "Provider reconciliation", "Webhook publication retention policy"),
        Local("IncomingWebhookMessage._payloadBytes", "Verified webhook principal resolves UserId", "Incoming webhook receiver", UserPiiDisposition.HardDelete),
        Local("StorageObject.Uri", "StorageObject.ActorId -> Actor.UserId", "Storage upload finalizer", UserPiiDisposition.HardDelete),
        Local("StorageObject.ObjectKey", "StorageObject.ActorId -> Actor.UserId", "Storage upload finalizer", UserPiiDisposition.HardDelete),
        Local("StorageObject.FullName", "StorageObject.ActorId -> Actor.UserId", "Storage upload finalizer", UserPiiDisposition.HardDelete),
        Local("StorageUploadSession.OriginalFileName", "StorageUploadSession.UserId", "CreateStorageUploadSessionCommandHandler", UserPiiDisposition.HardDelete),
        Local("StorageUploadSession.ObjectKey", "StorageUploadSession.UserId", "CreateStorageUploadSessionCommandHandler", UserPiiDisposition.HardDelete),
        Local("PdsSyncOutbox.Did", "PdsSyncOutbox.UserId", "ATProto publication planner", UserPiiDisposition.HardDelete),
        Local("PdsSyncOutbox.Payload", "PdsSyncOutbox.UserId", "ATProto publication planner", UserPiiDisposition.HardDelete),
        Local("PdsSyncOutbox.PdsHost", "PdsSyncOutbox.UserId", "ATProto publication planner", UserPiiDisposition.HardDelete),
        Local("UserAuthenticationToken.UserId", "UserAuthenticationToken.UserId", "ATProto OAuth session store", UserPiiDisposition.HardDelete),
        Local("UserAuthenticationToken.SubjectDid", "UserAuthenticationToken.UserId", "ATProto OAuth session store", UserPiiDisposition.HardDelete),
        Local("UserAuthenticationToken.SessionCiphertext", "UserAuthenticationToken.UserId", "ATProto OAuth session store", UserPiiDisposition.HardDelete),
        Local("UserAuthenticationToken.PdsHost", "UserAuthenticationToken.UserId", "ATProto OAuth session store", UserPiiDisposition.HardDelete),
        Local("UserExternalLogin.ProviderKey", "UserExternalLogin.UserId", "SyncUserCommandHandler", UserPiiDisposition.HardDelete),
        Local("ExternalApiKey.SecretHash", "ExternalApiKey.OwnerId when owner type is User", "External API-key handlers", UserPiiDisposition.HardDelete),
        Local("AuditLog.ActorId", "AuditLog.ActorId", "Audit interceptor", UserPiiDisposition.Anonymize,
            "Security and compliance evidence", "Configured audit retention horizon"),
        Local("AuditLog.OldValues", "AuditLog.ActorId", "Audit interceptor", UserPiiDisposition.Anonymize,
            "Security and compliance evidence", "Configured audit retention horizon"),
        Local("AuditLog.NewValues", "AuditLog.ActorId", "Audit interceptor", UserPiiDisposition.Anonymize,
            "Security and compliance evidence", "Configured audit retention horizon"),
        Local("UserPreference.Value", "UserPreference.UserId", "User preference handlers", UserPiiDisposition.HardDelete),
        Local("UserAppearanceProfile.UserId", "UserAppearanceProfile.UserId", "User appearance profile handlers", UserPiiDisposition.HardDelete),
        Local("UserAppearanceProfile.Name", "UserAppearanceProfile.UserId", "User appearance profile handlers", UserPiiDisposition.HardDelete),
        Local("EventReport.ReporterUserId", "EventReport.ReporterUserId", "Event report intake", UserPiiDisposition.Anonymize,
            "Preserve the shared trust-and-safety case", "Report retention horizon"),
        Local("EventReport.ReporterActorId", "EventReport.ReporterUserId", "Event report intake", UserPiiDisposition.Anonymize,
            "Preserve the shared trust-and-safety case", "Report retention horizon"),
        Local("EventReport.ReporterLocale", "EventReport.ReporterUserId", "Event report intake", UserPiiDisposition.Anonymize,
            "Preserve the shared trust-and-safety case", "Report retention horizon"),
        Local("EventReport.ReporterIpHash", "EventReport.ReporterUserId", "Event report intake", UserPiiDisposition.Anonymize,
            "Preserve the shared trust-and-safety case", "Report retention horizon"),
        Local("EventReport.ReporterUserAgentHash", "EventReport.ReporterUserId", "Event report intake", UserPiiDisposition.Anonymize,
            "Preserve the shared trust-and-safety case", "Report retention horizon"),
        Local("EventReportEvidence.CreatedByUserId", "EventReportEvidence.CreatedByUserId", "Event report intake", UserPiiDisposition.Anonymize,
            "Preserve the shared trust-and-safety case", "Report retention horizon"),
        Local("EventReportEvidence.TextBodyEncrypted", "EventReportEvidence.CreatedByUserId", "Event report intake", UserPiiDisposition.HardDelete),
        Local("ConfigurationChangeLog.UserId", "ConfigurationChangeLog.UserId", "Configuration governance service", UserPiiDisposition.Anonymize,
            "Configuration accountability", "Configured change-log retention horizon"),
        Local("IdempotencyRecord.UserId", "IdempotencyRecord.UserId", "Idempotency middleware", UserPiiDisposition.HardDelete),
        Local("IdempotencyRecord.ResponseBody", "IdempotencyRecord.UserId", "Idempotency middleware", UserPiiDisposition.HardDelete),

        Local("Actor.UserId", "Actor.UserId", "Actor handlers", UserPiiDisposition.Anonymize,
            "Preserve shared authorship without identity", "Permanent anonymous tombstone"),
        Local("AtprotoIdentity.PdsHost", "Actor.UserId -> AtprotoIdentity.ActorId", "ATProto actor synchronization", UserPiiDisposition.HardDelete),
        Local("ActorSubscription.SubscriberTenantUserId", "ActorSubscription.SubscriberUserId", "Actor subscription handlers", UserPiiDisposition.HardDelete),
        Local("ActorSubscription.SubscriberUserId", "ActorSubscription.SubscriberUserId", "Actor subscription handlers", UserPiiDisposition.HardDelete),
        Local("AiConsentGrant.SubjectUserId", "AiConsentGrant.SubjectUserId", "AI consent handlers", UserPiiDisposition.HardDelete),
        Local("AiConsentGrant.EntityName", "AiConsentGrant.SubjectUserId", "AI consent handlers", UserPiiDisposition.HardDelete),
        Local("AiConsentGrant.FieldName", "AiConsentGrant.SubjectUserId", "AI consent handlers", UserPiiDisposition.HardDelete),
        Local("AiConversation.Title", "AiConversation.UserId", "AI conversation handlers", UserPiiDisposition.HardDelete),
        Local("AiRun.FailureMessage", "Run -> AiConversation.UserId", "AI orchestration", UserPiiDisposition.HardDelete),
        Local("AiProposedAction.FailureMessage", "Conversation -> AiConversation.UserId", "AI tool orchestration", UserPiiDisposition.HardDelete),
        Local("AiToolExecution.ToolName", "Proposed action -> conversation -> UserId", "AI tool orchestration", UserPiiDisposition.HardDelete),
        Local("AtprotoOutboundRecordOwnership.UserId", "AtprotoOutboundRecordOwnership.UserId", "ATProto publication planner", UserPiiDisposition.HardDelete),
        Local("ConfigurationChangeLog.NewValue", "ConfigurationChangeLog.UserId", "Configuration governance service", UserPiiDisposition.Anonymize,
            "Configuration accountability", "Configured change-log retention horizon"),
        Local("ConfigurationChangeLog.OldValue", "ConfigurationChangeLog.UserId", "Configuration governance service", UserPiiDisposition.Anonymize,
            "Configuration accountability", "Configured change-log retention horizon"),
        Local("EmailDispatchOutbox.ProviderMessageId", "EmailDispatchOutbox.RecipientUserId", "EmailDispatchDrainService", UserPiiDisposition.HardDelete),
        Local("EmailDispatchOutbox.RecipientUserId", "EmailDispatchOutbox.RecipientUserId", "EventLifecycleEmailOutboxFactory", UserPiiDisposition.HardDelete),
        Local("EmailDispatchReceipt.FailureMessage", "Receipt -> EmailDispatchOutbox.RecipientUserId", "EmailDispatchDrainService", UserPiiDisposition.Anonymize,
            "Delivery reconciliation and abuse handling", "Delivery receipt retention policy"),
        Local("EmailDispatchReceipt.ProviderMessageId", "Receipt -> EmailDispatchOutbox.RecipientUserId", "EmailDispatchDrainService", UserPiiDisposition.Anonymize,
            "Delivery reconciliation and abuse handling", "Delivery receipt retention policy"),
        Local("EventContactShareConsent.UserId", "EventContactShareConsent.UserId", "Contact-share consent handler", UserPiiDisposition.HardDelete),
        Local("EventLocation.LastPolicyActorUserId", "EventLocation.LastPolicyActorUserId", "Location policy handlers", UserPiiDisposition.Anonymize,
            "Location policy accountability", "Configured audit retention horizon"),
        Local("EventLocationDisclosureAudit.ActorUserId", "EventLocationDisclosureAudit.ActorUserId", "Location disclosure audit", UserPiiDisposition.BoundedRetain,
            "Security and compliance evidence", "Configured audit retention horizon"),
        Local("EventLocationExactReadAudit.RequesterUserId", "EventLocationExactReadAudit.RequesterUserId", "Location exact-read audit", UserPiiDisposition.BoundedRetain,
            "Security and compliance evidence", "Configured audit retention horizon"),
        Local("EventModerationRecord.ModeratorUserId", "EventModerationRecord.ModeratorUserId", "Event moderation handlers", UserPiiDisposition.Anonymize,
            "Trust-and-safety accountability", "Moderation retention horizon"),
        Local("EventReportCase.AssignedModeratorUserId", "EventReportCase.AssignedModeratorUserId", "Event report case handlers", UserPiiDisposition.Anonymize,
            "Trust-and-safety accountability", "Report retention horizon"),
        Local("EventReportDecision.ModeratorUserId", "EventReportDecision.ModeratorUserId", "Event report decision handlers", UserPiiDisposition.Anonymize,
            "Trust-and-safety accountability", "Report retention horizon"),
        Local("EventReportEvidence.ContentHash", "EventReportEvidence.CreatedByUserId", "Event report intake", UserPiiDisposition.HardDelete),
        Local("EventRoleAssignment.RevokedByUserId", "EventRoleAssignment.RevokedByUserId", "Event role handlers", UserPiiDisposition.Anonymize,
            "Role-change accountability", "Configured audit retention horizon"),
        Local("EventRoleAssignment.UserId", "EventRoleAssignment.UserId", "Event role handlers", UserPiiDisposition.HardDelete),
        Local("ExternalApiKey.Name", "ExternalApiKey.OwnerId when owner type is User", "External API-key handlers", UserPiiDisposition.HardDelete),
        Local("GroupMember.UserId", "GroupMember.UserId", "Group membership handlers", UserPiiDisposition.HardDelete),
        Local("IdempotencyRecord.ContentType", "IdempotencyRecord.UserId", "Idempotency middleware", UserPiiDisposition.HardDelete),
        Local("IdempotencyRecord.RequestBodyHash", "IdempotencyRecord.UserId", "Idempotency middleware", UserPiiDisposition.HardDelete),
        Local("IdempotencyRecord.RequestContentType", "IdempotencyRecord.UserId", "Idempotency middleware", UserPiiDisposition.HardDelete),
        Local("IncomingWebhookMessage.ContentEncoding", "Verified webhook principal resolves UserId", "Incoming webhook receiver", UserPiiDisposition.HardDelete),
        Local("IncomingWebhookMessage.ContentType", "Verified webhook principal resolves UserId", "Incoming webhook receiver", UserPiiDisposition.HardDelete),
        Local("IncomingWebhookMessage.PayloadHash", "Verified webhook principal resolves UserId", "Incoming webhook receiver", UserPiiDisposition.HardDelete),
        Local("IncomingWebhookMessage.ProviderMessageId", "Verified webhook principal resolves UserId", "Incoming webhook receiver", UserPiiDisposition.HardDelete),
        Local("InstanceBootstrapState.CompletedByUserId", "InstanceBootstrapState.CompletedByUserId", "Instance bootstrap workflow", UserPiiDisposition.Anonymize,
            "Platform bootstrap accountability", "Configured audit retention horizon"),
        Local("Location.OwnerUserId", "Location.OwnerUserId", "Location handlers", UserPiiDisposition.HardDelete),
        Local("Location.FullName", "Location.OwnerUserId", "Location handlers", UserPiiDisposition.HardDelete),
        Local("PrivacyErasureIntent.SubjectId", "PrivacyErasureIntent.SubjectId", "Privacy erasure authority", UserPiiDisposition.BoundedRetain,
            "Durable erasure replay authority", "Configured authority retention horizon"),
        Local("ManagedTenantProvisioningOperation.TenantAdministratorUserId", "ManagedTenantProvisioningOperation.TenantAdministratorUserId", "Managed tenant provisioning", UserPiiDisposition.Anonymize,
            "Provisioning accountability", "Configured provisioning retention horizon"),
        Local("NotificationChannelPreference.UserId", "NotificationChannelPreference.UserId", "Notification preference handlers", UserPiiDisposition.HardDelete),
        Local("NotificationExternalDelegation.SafePayloadHash", "Notification intent RecipientUserId", "External notification delegation worker", UserPiiDisposition.HardDelete),
        Local("NotificationFanoutRun.CursorSubscriberTenantUserId", "NotificationFanoutRun.CursorSubscriberTenantUserId", "Notification fanout coordinator", UserPiiDisposition.HardDelete),
        Local("NotificationFanoutRun.CursorUserId", "NotificationFanoutRun.CursorUserId", "Notification fanout coordinator", UserPiiDisposition.HardDelete),
        Local("NotificationIntent.RecipientUserId", "NotificationIntent.RecipientUserId", "DefaultNotificationOrchestrator", UserPiiDisposition.HardDelete),
        Local("NotificationIntent.SafePayloadHash", "NotificationIntent.RecipientUserId", "DefaultNotificationOrchestrator", UserPiiDisposition.HardDelete),
        Local("NotificationPreferenceProfile.UserId", "NotificationPreferenceProfile.UserId", "Notification preference handlers", UserPiiDisposition.HardDelete),
        Local("OrganizationMember.UserId", "OrganizationMember.UserId", "Organization membership handlers", UserPiiDisposition.HardDelete),
        Local("OrganizationTenantEvidence.CreatedBy", "OrganizationTenantEvidence.CreatedBy", "Organization evidence submission", UserPiiDisposition.BoundedRetain,
            "Participation legitimacy review audit", "Organization evidence retention policy"),
        Local("OrganizationTenantEvidence.ReviewedByUserId", "OrganizationTenantEvidence.ReviewedByUserId", "Organization evidence review", UserPiiDisposition.BoundedRetain,
            "Participation legitimacy review audit", "Organization evidence retention policy"),
        Local("OrganizationTenantEvidence.ReviewNotes", "OrganizationTenantEvidence.ReviewedByUserId", "Organization evidence review", UserPiiDisposition.BoundedRetain,
            "Participation legitimacy review rationale", "Organization evidence retention policy"),
        Local("OrganizationTenantEvidence.UpdatedBy", "OrganizationTenantEvidence.UpdatedBy", "Organization evidence review", UserPiiDisposition.BoundedRetain,
            "Participation legitimacy review audit", "Organization evidence retention policy"),
        Local("OrganizationReview.UserId", "OrganizationReview.UserId", "Organization review handlers", UserPiiDisposition.Anonymize,
            "Preserve shared review content without identity", "Review retention horizon"),
        Local("OrganizationReview.ReviewerName", "OrganizationReview.UserId", "Organization review handlers", UserPiiDisposition.Anonymize,
            "Preserve shared review content without identity", "Review retention horizon"),
        Local("PdsSyncOutbox.PayloadHash", "PdsSyncOutbox.UserId", "ATProto publication planner", UserPiiDisposition.HardDelete),
        Local("PdsSyncOutbox.SettledUri", "PdsSyncOutbox.UserId", "ATProto publication planner", UserPiiDisposition.HardDelete),
        Local("PdsSyncOutbox.UserId", "PdsSyncOutbox.UserId", "ATProto publication planner", UserPiiDisposition.HardDelete),
        Local("PlatformUserRole.UserId", "PlatformUserRole.UserId", "Platform role handlers", UserPiiDisposition.HardDelete),
        Local("StorageObject.ContentType", "StorageObject.ActorId -> Actor.UserId", "Storage upload finalizer", UserPiiDisposition.HardDelete),
        Local("StorageObject.SafeDisplayName", "StorageObject.ActorId -> Actor.UserId", "Storage upload finalizer", UserPiiDisposition.HardDelete),
        Local("StorageUploadSession.ContentType", "StorageUploadSession.UserId", "CreateStorageUploadSessionCommandHandler", UserPiiDisposition.HardDelete),
        Local("StorageUploadSession.FailureMessage", "StorageUploadSession.UserId", "CreateStorageUploadSessionCommandHandler", UserPiiDisposition.HardDelete),
        Local("StorageUploadSession.SafeDisplayName", "StorageUploadSession.UserId", "CreateStorageUploadSessionCommandHandler", UserPiiDisposition.HardDelete),
        Local("StorageUploadSession.UserId", "StorageUploadSession.UserId", "CreateStorageUploadSessionCommandHandler", UserPiiDisposition.HardDelete),
        Local("SupportAccessAuditEvent.ActorUserId", "SupportAccessAuditEvent.ActorUserId", "Support access audit", UserPiiDisposition.Anonymize,
            "Privileged-access accountability", "Configured support audit retention horizon"),
        Local("SupportAccessAuditEvent.TargetTenantUserId", "SupportAccessAuditEvent.TargetTenantUserId", "Support access audit", UserPiiDisposition.Anonymize,
            "Privileged-access accountability", "Configured support audit retention horizon"),
        Local("SupportAccessAuditEvent.RequestName", "SupportAccessAuditEvent.ActorUserId", "Support access audit", UserPiiDisposition.Anonymize,
            "Privileged-access accountability", "Configured support audit retention horizon"),
        Local("SupportAccessAuditEvent.RouteName", "SupportAccessAuditEvent.ActorUserId", "Support access audit", UserPiiDisposition.Anonymize,
            "Privileged-access accountability", "Configured support audit retention horizon"),
        Local("SupportAccessSession.ActorUserId", "SupportAccessSession.ActorUserId", "Support access workflow", UserPiiDisposition.Anonymize,
            "Privileged-access accountability", "Configured support audit retention horizon"),
        Local("SupportAccessSession.ApprovedByUserId", "SupportAccessSession.ApprovedByUserId", "Support access workflow", UserPiiDisposition.Anonymize,
            "Privileged-access accountability", "Configured support audit retention horizon"),
        Local("SupportAccessSession.TargetTenantUserId", "SupportAccessSession.TargetTenantUserId", "Support access workflow", UserPiiDisposition.Anonymize,
            "Privileged-access accountability", "Configured support audit retention horizon"),
        Local("TenantInvitation.AcceptedByUserId", "TenantInvitation.AcceptedByUserId", "Tenant invitation handlers", UserPiiDisposition.Anonymize,
            "Invitation security audit", "Invitation expiry plus 30 days"),
        Local("TenantLifecycleLog.TransitionedByUserId", "TenantLifecycleLog.TransitionedByUserId", "Tenant lifecycle workflow", UserPiiDisposition.Anonymize,
            "Tenant lifecycle accountability", "Configured audit retention horizon"),
        Local("TenantOnboardingState.CompletedByUserId", "TenantOnboardingState.CompletedByUserId", "Tenant onboarding workflow", UserPiiDisposition.Anonymize,
            "Tenant onboarding accountability", "Configured audit retention horizon"),
        Local("TenantPlanApplicationLog.AppliedByUserId", "TenantPlanApplicationLog.AppliedByUserId", "Tenant plan workflow", UserPiiDisposition.Anonymize,
            "Tenant plan accountability", "Configured audit retention horizon"),
        Local("TenantPlanAssignment.AssignedByUserId", "TenantPlanAssignment.AssignedByUserId", "Tenant plan workflow", UserPiiDisposition.Anonymize,
            "Tenant plan accountability", "Configured audit retention horizon"),
        Local("TenantUser.ModerationNote", "TenantUser.UserId", "Tenant membership handlers", UserPiiDisposition.HardDelete),
        Local("TenantUserProfile.TenantUserId", "TenantUserProfile.TenantUserId -> TenantUser.UserId", "Tenant profile handlers", UserPiiDisposition.HardDelete),
        Local("TenantUserProfile.ContactEmailOverride", "TenantUserProfile.TenantUserId -> TenantUser.UserId", "Tenant profile handlers", UserPiiDisposition.HardDelete),
        Local("TenantUserProfile.DisplayNameOverride", "TenantUserProfile.TenantUserId -> TenantUser.UserId", "Tenant profile handlers", UserPiiDisposition.HardDelete),
        Local("TenantUserProfile.Locale", "TenantUserProfile.TenantUserId -> TenantUser.UserId", "Tenant profile handlers", UserPiiDisposition.HardDelete),
        Local("TenantUserRoleGrant.TenantUserId", "TenantUserRoleGrant.TenantUserId -> TenantUser.UserId", "Tenant role handlers", UserPiiDisposition.HardDelete),
        Local("UserAppearancePreference.UserId", "UserAppearancePreference.UserId", "User appearance preference handlers", UserPiiDisposition.HardDelete),
        Local("UserExternalLogin.ProviderDisplayName", "UserExternalLogin.UserId", "SyncUserCommandHandler", UserPiiDisposition.HardDelete),
        Local("UserExternalLogin.UserId", "UserExternalLogin.UserId", "SyncUserCommandHandler", UserPiiDisposition.HardDelete),
        Local("UserNotificationPreference.UserId", "UserNotificationPreference.UserId", "Notification preference handlers", UserPiiDisposition.HardDelete),
        Local("UserPii.UserId", "UserPii.UserId", "SyncUserCommandHandler", UserPiiDisposition.HardDelete),
        Local("UserPreference.UserId", "UserPreference.UserId", "User preference handlers", UserPiiDisposition.HardDelete),
        Local("WebPushDispatchOutbox.UserId", "WebPushDispatchOutbox.UserId", "Web-push fanout", UserPiiDisposition.HardDelete),
        Local("WebPushSubscription.UserId", "WebPushSubscription.UserId", "Web-push subscription handlers", UserPiiDisposition.HardDelete),
        Local("WebhookConsumer.OwnerUserId", "WebhookConsumer.OwnerUserId", "Webhook consumer handlers", UserPiiDisposition.HardDelete),
        Local("WebhookConsumer.Name", "WebhookConsumer.OwnerUserId", "Webhook consumer handlers", UserPiiDisposition.HardDelete),
        Local("WebhookMessage.ContentEncoding", "Webhook aggregate ownership resolves UserId", "DefaultWebhookPayloadBuilder", UserPiiDisposition.HardDelete),
        Local("WebhookMessage.ContentType", "Webhook aggregate ownership resolves UserId", "DefaultWebhookPayloadBuilder", UserPiiDisposition.HardDelete),
        Local("WebhookMessage.PayloadHash", "Webhook aggregate ownership resolves UserId", "DefaultWebhookPayloadBuilder", UserPiiDisposition.HardDelete),
        Local("WebhookProviderPublication.CredentialReference", "Webhook consumer owner UserId", "Webhook provider publisher", UserPiiDisposition.HardDelete),
        Local("WebhookProviderPublication.CredentialVersion", "Webhook consumer owner UserId", "Webhook provider publisher", UserPiiDisposition.HardDelete),
        Local("WebhookProviderPublication.ExternalProviderMessageId", "Webhook consumer owner UserId", "Webhook provider publisher", UserPiiDisposition.HardDelete),
        Local("ActorKeyStore.PrivateKeyEncrypted", "ActorKeyStore.ActorId -> Actor.UserId", "Actor key-store handlers", UserPiiDisposition.HardDelete),
        Local("ActorKeyStore.PublicKey", "ActorKeyStore.ActorId -> Actor.UserId", "Actor key-store handlers", UserPiiDisposition.HardDelete),
        Local("AiConversationReference.DisplayName", "Reference -> AiConversation.UserId", "AI context gateway", UserPiiDisposition.HardDelete),
        Local("Event.Content", "Event.ActorId -> Actor.UserId", "Event handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("Event.EventTimeZoneId", "Event.ActorId -> Actor.UserId", "Event handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventPublicAction.Url", "EventPublicAction.EventId -> Event.ActorId -> Actor.UserId", "Event public-action handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("Event.Timezone", "Event.ActorId -> Actor.UserId", "Event handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("Event.Title", "Event.ActorId -> Actor.UserId", "Event handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventAgendaItem.Title", "Agenda item -> Event.ActorId -> Actor.UserId", "Event agenda handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventCustomPropertyDefinition.AllowedUrlSchemes", "Definition -> Event.ActorId -> Actor.UserId", "Event custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventCustomPropertyDefinition.DefaultTextValue", "Definition -> Event.ActorId -> Actor.UserId", "Event custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventCustomPropertyDefinition.DisplayName", "Definition -> Event.ActorId -> Actor.UserId", "Event custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventCustomPropertyDefinition.Namespace", "Definition -> Event.ActorId -> Actor.UserId", "Event custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventCustomPropertyOption.DisplayName", "Option -> definition -> Event.ActorId -> Actor.UserId", "Event custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventCustomPropertyOption.Namespace", "Option -> definition -> Event.ActorId -> Actor.UserId", "Event custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventCustomPropertyOption.Value", "Option -> definition -> Event.ActorId -> Actor.UserId", "Event custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventCustomPropertyProjection.Namespace", "Projection -> Event.ActorId -> Actor.UserId", "Event custom-property projection", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventCustomPropertyProjection.NormalizedValue", "Projection -> Event.ActorId -> Actor.UserId", "Event custom-property projection", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventCustomPropertyProjection.TextValue", "Projection -> Event.ActorId -> Actor.UserId", "Event custom-property projection", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventCustomPropertyValue.TextValue", "Value -> Event.ActorId -> Actor.UserId", "Event custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventReportExternalLink.ProviderUrl", "External link -> EventReport.ReporterUserId", "Event report provider sync", UserPiiDisposition.HardDelete),
        Local("EventSeries.Title", "Series -> Event.ActorId -> Actor.UserId", "Event series handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventSession.Title", "Session -> Event.ActorId -> Actor.UserId", "Event session handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventSessionAgendaItem.Title", "Agenda item -> session -> Event.ActorId -> Actor.UserId", "Event session agenda handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventSessionCustomPropertyDefinition.AllowedUrlSchemes", "Definition -> session -> Event.ActorId -> Actor.UserId", "Session custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventSessionCustomPropertyDefinition.DefaultTextValue", "Definition -> session -> Event.ActorId -> Actor.UserId", "Session custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventSessionCustomPropertyDefinition.DisplayName", "Definition -> session -> Event.ActorId -> Actor.UserId", "Session custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventSessionCustomPropertyDefinition.Namespace", "Definition -> session -> Event.ActorId -> Actor.UserId", "Session custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventSessionCustomPropertyOption.DisplayName", "Option -> definition -> session -> Event.ActorId -> Actor.UserId", "Session custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventSessionCustomPropertyOption.Namespace", "Option -> definition -> session -> Event.ActorId -> Actor.UserId", "Session custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventSessionCustomPropertyOption.Value", "Option -> definition -> session -> Event.ActorId -> Actor.UserId", "Session custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventSessionCustomPropertyProjection.Namespace", "Projection -> session -> Event.ActorId -> Actor.UserId", "Session custom-property projection", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventSessionCustomPropertyProjection.NormalizedValue", "Projection -> session -> Event.ActorId -> Actor.UserId", "Session custom-property projection", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventSessionCustomPropertyProjection.TextValue", "Projection -> session -> Event.ActorId -> Actor.UserId", "Session custom-property projection", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventSessionCustomPropertyValue.TextValue", "Value -> session -> Event.ActorId -> Actor.UserId", "Session custom-property handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventSessionGroup.Name", "Session group -> Event.ActorId -> Actor.UserId", "Event session group handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("EventTechAspect.GithubRepoUrl", "Tech aspect -> Event.ActorId -> Actor.UserId", "Event tech-aspect handlers", UserPiiDisposition.Anonymize,
            "Preserve shared published content after identity removal", "Shared-content retention horizon"),
        Local("Group.FullName", "Group membership -> GroupMember.UserId", "Group handlers", UserPiiDisposition.Anonymize,
            "Preserve shared group content after member identity removal", "Shared-content retention horizon"),
        Local("GroupSetting.Value", "Group membership -> GroupMember.UserId", "Group setting handlers", UserPiiDisposition.Anonymize,
            "Preserve shared group configuration after identity removal", "Configuration retention horizon"),
        Local("IncomingWebhookEffectOutbox.PayloadSha256", "Incoming webhook ownership resolves UserId", "Incoming webhook effect processor", UserPiiDisposition.HardDelete),
        Local("IncomingWebhookEffectReceipt.PayloadHash", "Incoming webhook ownership resolves UserId", "Incoming webhook effect processor", UserPiiDisposition.HardDelete),
        Local("Location.Timezone", "Location.OwnerUserId", "Location handlers", UserPiiDisposition.HardDelete),
        Local("LocationRoom.Name", "Room -> Location.OwnerUserId", "Location room handlers", UserPiiDisposition.HardDelete),
        Local("TenantUserProfile.AdminNote", "TenantUserProfile.TenantUserId -> TenantUser.UserId", "Tenant profile handlers", UserPiiDisposition.HardDelete),
        Local("TenantUserProfile.ConsentJson", "TenantUserProfile.TenantUserId -> TenantUser.UserId", "Tenant profile handlers", UserPiiDisposition.HardDelete),
        Local("TenantUserProfile.PreferencesJson", "TenantUserProfile.TenantUserId -> TenantUser.UserId", "Tenant profile handlers", UserPiiDisposition.HardDelete),
        Local("TenantUserProfile.TimeZone", "TenantUserProfile.TenantUserId -> TenantUser.UserId", "Tenant profile handlers", UserPiiDisposition.HardDelete),
        Local("WebhookEndpoint.PreviousSecretRef", "Endpoint -> WebhookConsumer.OwnerUserId", "Webhook endpoint handlers", UserPiiDisposition.HardDelete),
        Local("WebhookEndpoint.ProviderEndpointId", "Endpoint -> WebhookConsumer.OwnerUserId", "Webhook endpoint handlers", UserPiiDisposition.HardDelete),
        Local("WebhookEndpoint.SecretRef", "Endpoint -> WebhookConsumer.OwnerUserId", "Webhook endpoint handlers", UserPiiDisposition.HardDelete),
        Local("WebhookEndpoint.Url", "Endpoint -> WebhookConsumer.OwnerUserId", "Webhook endpoint handlers", UserPiiDisposition.HardDelete),
        Local("WebhookProviderPublicationAttempt.ExternalProviderMessageId", "Publication -> WebhookConsumer.OwnerUserId", "Webhook provider publisher", UserPiiDisposition.HardDelete),

        External("provider:keycloak:platform-managed-account", "UserExternalLogin.ProviderKey", "Keycloak identity adapter",
            UserPiiProviderAction.DeletePlatformManagedIdentity,
            typeof(Explore.Infrastructure.Services.Keycloak.KeycloakBootstrapService)),
        External("provider:keycloak:upstream-session", "UserExternalLogin.ProviderKey", "Keycloak identity adapter",
            UserPiiProviderAction.RevokeOrUnlinkExternalIdentity,
            typeof(Explore.Infrastructure.Services.Keycloak.KeycloakAccountAuthorityLifecycleEmailService)),
        External("provider:atproto:pds-account", "Actor.UserId + AtprotoIdentity.Did", "ATProto PDS adapter",
            UserPiiProviderAction.RevokeOrUnlinkExternalIdentity,
            typeof(Explore.Infrastructure.Services.Federation.AtprotoOAuthSecurityGateway),
            typeof(Explore.Infrastructure.Services.Federation.AtprotoPdsDeliveryGateway)),
        External("provider:listmonk:subscriber", "EmailDispatchOutbox.UserId", "Listmonk integration worker",
            UserPiiProviderAction.DeleteOrAnonymizeProviderCopy,
            typeof(Explore.Infrastructure.Integrations.Listmonk.ListmonkSyncService)),
        External("provider:smtp:delivered-message", "EmailDispatchOutbox.UserId", "SMTP dispatch worker",
            UserPiiProviderAction.ExpireLocalMetadataWithoutRecall,
            typeof(Explore.Infrastructure.Mail.SmtpEmailService)),
        External("provider:web-push:endpoint", "WebPushSubscription.UserId", "Web-push sender",
            UserPiiProviderAction.InvalidateSubscription,
            typeof(Explore.Infrastructure.WebPush.WebPushNotificationSender)),
        External("provider:object-storage:user-object", "StorageObject.ActorId -> Actor.UserId", "File storage provider",
            UserPiiProviderAction.DeleteOwnedObject,
            typeof(Explore.Infrastructure.Storage.S3FileStorageProvider),
            typeof(Explore.Infrastructure.Services.ObjectStorageService)),
        External("provider:svix:payload", "Webhook consumer owner UserId", "Svix publisher",
            UserPiiProviderAction.DeleteOrAnonymizeProviderCopy,
            typeof(Explore.Infrastructure.Webhooks.ISvixWebhookClient)),
        External("provider:ai:retained-context", "AiConversation.UserId", "AI context gateway",
            UserPiiProviderAction.PurgeRetainedContext,
            typeof(Explore.Application.Features.AiAssistant.Disclosure.AiContextGateway)),
        External("provider:webhook:payload", "Webhook aggregate ownership resolves UserId", "Webhook delivery worker",
            UserPiiProviderAction.CorrectOrDeleteProviderCopy,
            typeof(Explore.Infrastructure.Webhooks.WebhookDeliveryDrainService)),
        External("provider:openai:retained-context", "AiConversation.UserId", "OpenAI Responses adapter",
            UserPiiProviderAction.PurgeRetainedContext,
            typeof(Explore.Infrastructure.Ai.OpenAiResponsesChatProvider)),
        External("provider:openai-compatible:retained-context", "AiConversation.UserId", "OpenAI-compatible adapter",
            UserPiiProviderAction.PurgeRetainedContext,
            typeof(Explore.Infrastructure.Ai.OpenAiCompatibleChatProvider)),
        External("provider:anthropic-compatible:retained-context", "AiConversation.UserId", "Anthropic-compatible adapter",
            UserPiiProviderAction.PurgeRetainedContext,
            typeof(Explore.Infrastructure.Ai.AnthropicCompatibleChatProvider)),
        External("provider:microsoft-extensions-ai:retained-context", "AiConversation.UserId", "Microsoft Extensions AI adapter",
            UserPiiProviderAction.PurgeRetainedContext,
            typeof(Explore.Infrastructure.Ai.MicrosoftExtensionsAiChatProvider)),
        External("provider:osprey:moderation-copy", "EventReport.ReporterUserId", "Osprey moderation adapter",
            UserPiiProviderAction.DeleteOrAnonymizeProviderCopy,
            typeof(Explore.Infrastructure.Services.Moderation.OspreyModerationSignalProvider)),
        External("provider:coop:review-queue-copy", "EventReport.ReporterUserId", "Cooperative review queue adapter",
            UserPiiProviderAction.DeleteOrAnonymizeProviderCopy,
            typeof(Explore.Infrastructure.Services.Moderation.Coop.CoopReviewQueueProvider))
    ];

    private static UserPiiInventoryEntry Local(
        string copy,
        string ownershipKey,
        string producer,
        UserPiiDisposition disposition,
        string retentionPurpose = "Account privacy erasure",
        string retentionHorizon = "Erase in the first committed local erasure transaction") =>
        new(copy, ownershipKey, producer, typeof(Explore.Domain.PrivacyErasureSaga), disposition,
            retentionPurpose, retentionHorizon, UserPiiProviderAction.None, CurrentPolicyVersion, []);

    private static UserPiiInventoryEntry External(
        string copy,
        string ownershipKey,
        string producer,
        UserPiiProviderAction providerAction,
        params Type[] providerSurfaces) =>
        new(copy, ownershipKey, producer, typeof(Explore.Domain.PrivacyErasureSaga), UserPiiDisposition.ExternalAction,
            "Provider-side privacy erasure",
            "Dispatch after local commit and settle under provider retry policy", providerAction, CurrentPolicyVersion, providerSurfaces);
}
