// ABOUTME: System.Text.Json source generator context for AOT compilation.
// ABOUTME: Registers browser-safe generated DTOs without provider credential contracts.

using System.Text.Json;
using System.Text.Json.Serialization;
using Explore.Blazor.Client.Clients;
using Explore.Blazor.Client.Models;
using Explore.Blazor.Client.Models.Events;
using Explore.Blazor.Client.Models.Responses;
using Explore.Blazor.Client.Pages.Events;
using Explore.Blazor.Client.Services.Docking;
using Explore.Blazor.Client.Services.Interop;

namespace Explore.Blazor.Client.Serialization;

/// <summary>
/// System.Text.Json source generator context for AOT-friendly JSON serialization.
/// Includes all DTOs used by the NSwag-generated EventApiClient and Blazor UI models.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false,
    AllowTrailingCommas = true)]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(ActorDto))]
[JsonSerializable(typeof(ActorListDto))]
[JsonSerializable(typeof(ActorTypeDto))]
[JsonSerializable(typeof(ActorTypeListDto))]
[JsonSerializable(typeof(AddOrganizationMemberDto))]
[JsonSerializable(typeof(AudienceAgeDto))]
[JsonSerializable(typeof(AudienceAgeListDto))]
[JsonSerializable(typeof(AudienceGenderDto))]
[JsonSerializable(typeof(AudienceGenderListDto))]
[JsonSerializable(typeof(BaseCommandResponseOfGuid))]
[JsonSerializable(typeof(BaseCommandResponseOfboolean))]
[JsonSerializable(typeof(BaseCommandResponseOfint))]
[JsonSerializable(typeof(CategoryDto))]
[JsonSerializable(typeof(CategoryListDto))]
[JsonSerializable(typeof(CreateCategoryDto))]
[JsonSerializable(typeof(CreateEventDraftRequestDto))]
[JsonSerializable(typeof(CreateEventSessionAgendaItemDto))]
[JsonSerializable(typeof(CreateEventSessionDto))]
[JsonSerializable(typeof(CreateLocationDto))]
[JsonSerializable(typeof(CreateOrganizationDto))]
[JsonSerializable(typeof(CreateOrganizationReviewDto))]
[JsonSerializable(typeof(CreateTagDto))]
[JsonSerializable(typeof(CreateTenantDto))]
[JsonSerializable(typeof(CreateTenantNavigationLinkDto))]
[JsonSerializable(typeof(CreateUpdateIslamicAspectDto))]
[JsonSerializable(typeof(CreateUpdateTechAspectDto))]
[JsonSerializable(typeof(DidCustodyTypeDto))]
[JsonSerializable(typeof(DidCustodyTypeListDto))]
[JsonSerializable(typeof(EventDto))]
[JsonSerializable(typeof(EventCreationContextDto))]
[JsonSerializable(typeof(EventCreationPublisherOptionDto))]
[JsonSerializable(typeof(EventPublishReadinessDto))]
[JsonSerializable(typeof(EventPublishReadinessErrorDto))]
[JsonSerializable(typeof(EventFormatDto))]
[JsonSerializable(typeof(EventFormatListDto))]
[JsonSerializable(typeof(EventIslamicAspectDto))]
[JsonSerializable(typeof(EventListDto))]
[JsonSerializable(typeof(EventDetail.EventDetailState))]
[JsonSerializable(typeof(DockLayoutSnapshot))]
[JsonSerializable(typeof(DockLayoutStorageEnvelope))]
[JsonSerializable(typeof(EventProgramDayGroupDto))]
[JsonSerializable(typeof(EventProgramItemDto))]
[JsonSerializable(typeof(EventProgramReadinessWarningDto))]
[JsonSerializable(typeof(EventProgramSectionDto))]
[JsonSerializable(typeof(EventProgramSessionGroupSectionDto))]
[JsonSerializable(typeof(EventProgramSummaryDto))]
[JsonSerializable(typeof(EventReportOptionsDto))]
[JsonSerializable(typeof(AssignModerationReportRequestDto))]
[JsonSerializable(typeof(DecideModerationReportRequestDto))]
[JsonSerializable(typeof(ExecuteModerationReportDecisionRequestDto))]
[JsonSerializable(typeof(ModerationReportDetailDto))]
[JsonSerializable(typeof(ModerationReportQueueItemDto))]
[JsonSerializable(typeof(TriageModerationReportRequestDto))]
[JsonSerializable(typeof(EventReportDecisionKind))]
[JsonSerializable(typeof(EventReportPriority))]
[JsonSerializable(typeof(EventSessionAgendaItemDto))]
[JsonSerializable(typeof(EventSessionAgendaItemListDto))]
[JsonSerializable(typeof(EventSessionCreateContextDto))]
[JsonSerializable(typeof(EventSessionCreateDefaultsDto))]
[JsonSerializable(typeof(EventSessionCreateGroupOptionDto))]
[JsonSerializable(typeof(EventSessionCreateLocationOptionDto))]
[JsonSerializable(typeof(EventSessionCreateRoomOptionDto))]
[JsonSerializable(typeof(EventSessionDto))]
[JsonSerializable(typeof(EventSessionKindListDto))]
[JsonSerializable(typeof(EventSessionLanguageDto))]
[JsonSerializable(typeof(EventSessionLanguageListDto))]
[JsonSerializable(typeof(EventSessionLifecycleRequestDto))]
[JsonSerializable(typeof(EventSessionListDto))]
[JsonSerializable(typeof(EventSessionSpeakerDto))]
[JsonSerializable(typeof(EventSessionSpeakerListDto))]
[JsonSerializable(typeof(EventStatusDto))]
[JsonSerializable(typeof(EventStatusListDto))]
[JsonSerializable(typeof(EventTechAspectDto))]
[JsonSerializable(typeof(EventTypeListDto))]
[JsonSerializable(typeof(FileTypeDto))]
[JsonSerializable(typeof(FileTypeListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfActorListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfCategoryListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfEventListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfEventSessionListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfModerationReportQueueItemDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfMyEventReportDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfLocationListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfOrganizationListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfOrganizationReviewDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfTagListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfActorListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfCategoryListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfEventListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfEventSessionListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfModerationReportQueueItemDto))]
[JsonSerializable(typeof(HalCollectionResourceOfMyEventReportDto))]
[JsonSerializable(typeof(HalCollectionResourceOfLocationListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfOrganizationListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfOrganizationReviewDto))]
[JsonSerializable(typeof(HalCollectionResourceOfTagListDto))]
[JsonSerializable(typeof(HalLink))]
[JsonSerializable(typeof(HalResourceOfActorDto))]
[JsonSerializable(typeof(HalResourceOfCategoryDto))]
[JsonSerializable(typeof(HalResourceOfEventDto))]
[JsonSerializable(typeof(HalResourceOfEventReportOptionsDto))]
[JsonSerializable(typeof(HalResourceOfEventSessionDto))]
[JsonSerializable(typeof(HalResourceOfModerationReportDetailDto))]
[JsonSerializable(typeof(HalResourceOfModerationReportQueueItemDto))]
[JsonSerializable(typeof(HalResourceOfMyEventReportDto))]
[JsonSerializable(typeof(HalResourceOfLocationDto))]
[JsonSerializable(typeof(HalResourceOfOrganizationDto))]
[JsonSerializable(typeof(HalResourceOfTagDto))]
[JsonSerializable(typeof(InstanceOnboardingStatusDto))]
[JsonSerializable(typeof(LanguageDto))]
[JsonSerializable(typeof(LanguageListDto))]
[JsonSerializable(typeof(LocationDto))]
[JsonSerializable(typeof(LocationListDto))]
[JsonSerializable(typeof(MadhabDto))]
[JsonSerializable(typeof(MadhabListDto))]
[JsonSerializable(typeof(ModuleActionResponse))]
[JsonSerializable(typeof(ModuleEnabledResponse))]
[JsonSerializable(typeof(ModuleInfo))]
[JsonSerializable(typeof(ModuleSchemaResponse))]
[JsonSerializable(typeof(MyEventReportDto))]
[JsonSerializable(typeof(OrganizationDto))]
[JsonSerializable(typeof(OrganizationInvitationDto))]
[JsonSerializable(typeof(OrganizationListDto))]
[JsonSerializable(typeof(OrganizationMemberDto))]
[JsonSerializable(typeof(OrganizationPositionDto))]
[JsonSerializable(typeof(OrganizationPositionListDto))]
[JsonSerializable(typeof(OrganizationReviewDto))]
[JsonSerializable(typeof(PaginatedResultOfEventSessionAgendaItemListDto))]
[JsonSerializable(typeof(HalCollectionEmbeddedOfStorageObjectListDto))]
[JsonSerializable(typeof(HalCollectionResourceOfStorageObjectListDto))]
[JsonSerializable(typeof(PresignedDownloadUrlResponseDto))]
[JsonSerializable(typeof(ProblemDetails))]
[JsonSerializable(typeof(PublicExperienceSettingsDto))]
[JsonSerializable(typeof(PublishEventRequestDto))]
[JsonSerializable(typeof(RegistrationModeDto))]
[JsonSerializable(typeof(RegistrationModeListDto))]
[JsonSerializable(typeof(StatusTypeListDto))]
[JsonSerializable(typeof(HalResourceOfStorageObjectDto))]
[JsonSerializable(typeof(SubmitEventReportDto))]
[JsonSerializable(typeof(TagDto))]
[JsonSerializable(typeof(TagListDto))]
[JsonSerializable(typeof(TagTypeDto))]
[JsonSerializable(typeof(TagTypeListDto))]
[JsonSerializable(typeof(TenantDto))]
[JsonSerializable(typeof(TenantListDto))]
[JsonSerializable(typeof(TenantNavigationLinkDto))]
[JsonSerializable(typeof(TenantOnboardingStatusDto))]
[JsonSerializable(typeof(TenantPolicySettingsDto))]
[JsonSerializable(typeof(UpdateCategoryDto))]
[JsonSerializable(typeof(EventDraftEditModel))]
[JsonSerializable(typeof(UpdateEventSessionAgendaItemDto))]
[JsonSerializable(typeof(UpdateEventSessionDto))]
[JsonSerializable(typeof(UpdateLocationDto))]
[JsonSerializable(typeof(UpdateOrganizationApprovalStatusDto))]
[JsonSerializable(typeof(UpdateOrganizationDto))]
[JsonSerializable(typeof(UpdateOrganizationMemberRoleDto))]
[JsonSerializable(typeof(UpdateStorageObjectDto))]
[JsonSerializable(typeof(UpdateTagDto))]
[JsonSerializable(typeof(UpdateTenantDto))]
[JsonSerializable(typeof(UpdateTenantNavigationLinkDto))]
[JsonSerializable(typeof(UpdateTenantNavigationLinkOrderDto))]
[JsonSerializable(typeof(UpdateUserDto))]
[JsonSerializable(typeof(UserAuthenticationTokenDto))]
[JsonSerializable(typeof(UserAuthenticationTokenListDto))]
[JsonSerializable(typeof(UserDto))]
[JsonSerializable(typeof(VisibilityTypeDto))]
[JsonSerializable(typeof(VisibilityTypeListDto))]
// Blazor Client Models
[JsonSerializable(typeof(ServiceResult))]
[JsonSerializable(typeof(TenantContext))]
[JsonSerializable(typeof(UserInfo))]
public partial class AppJsonSerializerContext : JsonSerializerContext
{
}
