// ABOUTME: Independent allowlist classifying every considered event and RSVP source field for federation.
// ABOUTME: Makes native mapping, description rendering, and privacy exclusions explicit and reviewable.

using System.Collections.Immutable;

namespace Explore.Application.Features.Federation.Atproto.Services;

public enum AtprotoSourceFieldDisposition
{
    Native = 1,
    Description = 2,
    Excluded = 3
}

public sealed record AtprotoSourceFieldManifestEntry(
    string SourcePath,
    AtprotoSourceFieldDisposition Disposition,
    string Reason);

public static class AtprotoEventSourceFieldManifest
{
    public static ImmutableArray<AtprotoSourceFieldManifestEntry> Entries { get; } =
    [
        Native("Event.Title", "community event name"),
        Native("Event.Description", "single rendered community event description"),
        Native("Event.CreatedAt", "community event createdAt"),
        Excluded("Event.FirstSessionStartUtc", "cached schedule rollup; native time derives from eligible sessions"),
        Description("Event.LastSessionStartUtc"),
        Excluded("Event.LastSessionEndUtc", "cached schedule rollup; native time derives from eligible sessions"),
        Native("Event.EventFormat", "community event mode"),
        Native("Event.EventStatus", "community event status"),
        Native("Event.EventUrl", "community event URI"),
        Native("Event.ExternalRegistrationUrl", "community event URI"),
        Native("Event.FeaturedImage", "community event URI"),
        Native("Event.BackgroundImage", "community event URI"),
        Native("Event.IsRegistrationRequired", "community event rsvpExpected"),
        Native("EventLocationDisclosureResult.Values", "community event native locations and description"),

        Description("Event.Subtitle"),
        Description("Event.Content"),
        Description("Event.EventType"),
        Description("Event.AudienceGender"),
        Description("Event.AudienceAge"),
        Description("Event.Price"),
        Description("Event.CurrencyCode"),
        Description("Event.TotalViews"),
        Description("Event.VisibilityType"),
        Description("Event.Madhab"),
        Description("Event.Slug"),
        Description("Event.PublicCode"),
        Description("Event.FirstSessionDate"),
        Description("Event.LastSessionDate"),
        Description("Event.Timezone"),
        Description("Event.EventTimeZoneId"),
        Description("Event.SessionCount"),
        Description("Event.RegistrationPolicy"),
        Description("Event.SeriesOrder"),
        Description("Event.BackgroundColor"),
        Description("Event.BackgroundEffect"),

        Description("Event.Actor.ActorType"),
        Description("Event.Actor.Pii.DisplayName"),
        Description("Event.Actor.Pii.Handle"),
        Description("Event.Actor.Description"),
        Description("Event.Actor.ProfilePicture"),
        Description("Event.Actor.BannerPicture"),
        Description("Event.Actor.BackgroundImage"),
        Description("Event.Actor.BackgroundColor"),
        Description("Event.Actor.BackgroundEffect"),
        Description("Event.Actor.BannerColor"),
        Description("Event.Actor.Organization.Pii.FullName"),
        Description("Event.Actor.Organization.WebsiteUrl"),
        Description("Event.Actor.Organization.Pii.Country"),
        Description("Event.Actor.Organization.Pii.City"),
        Description("Event.Actor.Group.FullName"),
        Description("Event.Actor.Group.Description"),
        Description("Event.Actor.Group.ProfilePicture"),

        Description("Event.EventSeries.Title"),
        Description("Event.EventSeries.Description"),
        Description("Event.EventSeries.Slug"),
        Description("Event.EventSeries.FeaturedImage"),
        Description("Event.EventSeries.IsPublished"),
        Excluded("Event.EventSeries.IsDeleted", "series eligibility gate, never payload"),
        Description("Event.EventSeries.TotalViews"),
        Description("Event.EventSeries.VisibilityType"),
        Description("Event.EventSeries.StartDateUtc"),
        Description("Event.EventSeries.EndDateUtc"),
        Description("Event.EventSeries.Actor.Pii.DisplayName"),

        Description("Event.IslamicAspect.Madhab"),
        Description("Event.IslamicAspect.ReferencePrayer"),
        Description("Event.IslamicAspect.PrayerTimeOffset"),
        Description("Event.IslamicAspect.GenderMode"),
        Description("Event.IslamicAspect.IncludesQuranRecitation"),
        Description("Event.IslamicAspect.PrimaryLanguage"),
        Description("Event.TechAspect.GithubRepoUrl"),
        Description("Event.TechAspect.HackathonTrack"),
        Description("Event.TechAspect.SkillLevel"),
        Description("Event.TechAspect.TechStackTags"),
        Description("Event.TechAspect.RequiresLaptop"),
        Description("Event.TechAspect.IsCodingCompetition"),
        Description("Event.TechAspect.MaxTeamSize"),
        Description("Event.TechAspect.PrizePool"),
        Description("Event.TechAspect.PrizeCurrencyCode"),

        Description("EventLocationDisclosureResult.State"),
        Description("EventLocationDisclosureResult.Values.Country"),
        Description("EventLocationDisclosureResult.Values.Timezone"),
        Description("EventLocationDisclosureResult.Values.City"),
        Description("EventLocationDisclosureResult.Values.VenueName"),
        Description("EventLocationDisclosureResult.Values.RoomName"),
        Description("EventLocationDisclosureResult.Values.RoomDescription"),
        Description("EventLocationDisclosureResult.Values.StreetAddress"),
        Description("EventLocationDisclosureResult.Values.Postcode"),
        Description("EventLocationDisclosureResult.Values.Latitude"),
        Description("EventLocationDisclosureResult.Values.Longitude"),
        Description("EventLocationDisclosureResult.Values.FormattedAddress"),
        Description("EventLocationDisclosureResult.Values.MapUrl"),
        Description("EventLocationDisclosureResult.Values.Geohash"),

        Description("EventDay.LocalDate"),
        Description("EventDay.Label"),
        Description("EventDay.Description"),
        Description("EventDay.BannerText"),
        Description("EventDay.BannerImage"),
        Description("EventDay.SortOrder"),
        Description("EventDay.AllowsDayScopeRegistration"),

        Description("EventSession.Title"),
        Description("EventSession.Description"),
        Native("EventSession.StartTime", "eligible sessions derive record startsAt and remain in the program description"),
        Native("EventSession.EndTime", "eligible sessions derive record endsAt and remain in the program description"),
        Description("EventSession.EndTimeType"),
        Description("EventSession.LocalStartDate"),
        Description("EventSession.LocalEndDate"),
        Description("EventSession.LocalStartTime"),
        Description("EventSession.LocalEndTime"),
        Excluded("EventSession.LocalStartMinuteOfDay", "cached local-time projection"),
        Excluded("EventSession.LocalEndMinuteOfDay", "cached local-time projection"),
        Description("EventSession.SortOrder"),
        Description("EventSession.Slug"),
        Description("EventSession.EventSessionKind"),
        Description("EventSession.EventSessionStatus"),
        Description("EventSession.MaxAudienceAttendees"),
        Description("EventSession.CurrentAudienceAttendees"),
        Description("EventSession.RegistrationMode"),
        Description("EventSession.FeaturedImage"),
        Description("EventSession.Price"),
        Description("EventSession.CurrencyCode"),
        Description("EventSession.Category"),
        Description("EventSession.Tag"),
        Description("EventSession.Language"),
        Description("EventSession.Speaker.Actor.Pii.DisplayName"),
        Description("EventSession.Speaker.Actor.Pii.Handle"),
        Description("EventSession.Speaker.Actor.Description"),
        Description("EventSession.Speaker.Actor.ProfilePicture"),
        Description("EventSession.IslamicAspect.StartTimeType"),
        Description("EventSession.IslamicAspect.ReferencePrayer"),
        Description("EventSession.IslamicAspect.OffsetMinutes"),
        Description("EventSession.IslamicAspect.EndReferencePrayer"),
        Description("EventSession.IslamicAspect.EndOffsetMinutes"),
        Description("EventSession.IslamicAspect.RequiresWudu"),
        Description("EventSession.IslamicAspect.RitualRequirementsJson"),

        Description("EventSessionGroup.Name"),
        Description("EventSessionGroup.Description"),
        Description("EventSessionGroup.Slug"),
        Description("EventSessionGroup.Color"),
        Description("EventSessionGroup.SortOrder"),
        Description("EventSessionGroupSession.IsPrimary"),
        Description("EventSessionGroupSession.SortOrder"),
        Description("EventAgendaItem.Title"),
        Description("EventAgendaItem.Description"),
        Description("EventAgendaItem.StartTime"),
        Description("EventAgendaItem.EndTime"),
        Description("EventAgendaItem.LocalStartDate"),
        Description("EventAgendaItem.LocalEndDate"),
        Description("EventAgendaItem.LocalStartTime"),
        Description("EventAgendaItem.LocalEndTime"),
        Description("EventAgendaItem.Kind"),
        Description("EventAgendaItem.SortOrder"),
        Description("EventSessionAgendaItem.Title"),
        Description("EventSessionAgendaItem.Description"),
        Description("EventSessionAgendaItem.StartTime"),
        Description("EventSessionAgendaItem.EndTime"),

        Description("Event.Category.Parent.FullName"),
        Description("Event.Category.FullName"),
        Description("Event.Tag.FullName"),
        Description("EventCustomPropertyDefinition.Namespace"),
        Description("EventCustomPropertyDefinition.Key"),
        Description("EventCustomPropertyDefinition.DisplayName"),
        Description("EventCustomPropertyDefinition.Description"),
        Description("EventCustomPropertyDefinition.PropertyType"),
        Description("EventCustomPropertyDefinition.IsRequired"),
        Description("EventCustomPropertyDefinition.IsMulti"),
        Description("EventCustomPropertyDefinition.IsActive"),
        Description("EventCustomPropertyDefinition.SortOrder"),
        Description("EventCustomPropertyDefinition.ExposureLevel"),
        Description("EventCustomPropertyDefinition.IsSearchable"),
        Description("EventCustomPropertyDefinition.IsFilterable"),
        Description("EventCustomPropertyDefinition.IsExportable"),
        Description("EventCustomPropertyDefinition.IsModerationRelevant"),
        Description("EventCustomPropertyDefinition.IsAnalyticsRelevant"),
        Description("EventCustomPropertyDefinition.IsSystemOwned"),
        Description("EventCustomPropertyDefinition.DefaultTextValue"),
        Description("EventCustomPropertyDefinition.DefaultNumberValue"),
        Description("EventCustomPropertyDefinition.DefaultBooleanValue"),
        Description("EventCustomPropertyDefinition.DefaultDateTimeValue"),
        Description("EventCustomPropertyDefinition.DefaultOption.DisplayName"),
        Description("EventCustomPropertyDefinition.MinLength"),
        Description("EventCustomPropertyDefinition.MaxLength"),
        Description("EventCustomPropertyDefinition.RegexPattern"),
        Description("EventCustomPropertyDefinition.MinNumber"),
        Description("EventCustomPropertyDefinition.MaxNumber"),
        Description("EventCustomPropertyDefinition.MinDateTime"),
        Description("EventCustomPropertyDefinition.MaxDateTime"),
        Description("EventCustomPropertyDefinition.AllowedUrlSchemes"),
        Description("EventCustomPropertyOption.Namespace"),
        Description("EventCustomPropertyOption.Key"),
        Description("EventCustomPropertyOption.DisplayName"),
        Description("EventCustomPropertyOption.Description"),
        Description("EventCustomPropertyOption.Value"),
        Description("EventCustomPropertyOption.IsDefault"),
        Description("EventCustomPropertyOption.IsActive"),
        Description("EventCustomPropertyOption.SortOrder"),
        Description("EventCustomPropertyOption.ParentOption.DisplayName"),
        Description("EventCustomPropertyValue.Ordinal"),
        Description("EventCustomPropertyValue.TextValue"),
        Description("EventCustomPropertyValue.NumberValue"),
        Description("EventCustomPropertyValue.BooleanValue"),
        Description("EventCustomPropertyValue.DateTimeValue"),
        Description("EventCustomPropertyValue.Option.DisplayName"),
        Description("EventSessionCustomPropertyDefinition.Namespace"),
        Description("EventSessionCustomPropertyDefinition.Key"),
        Description("EventSessionCustomPropertyDefinition.DisplayName"),
        Description("EventSessionCustomPropertyDefinition.Description"),
        Description("EventSessionCustomPropertyDefinition.PropertyType"),
        Description("EventSessionCustomPropertyDefinition.IsRequired"),
        Description("EventSessionCustomPropertyDefinition.IsMulti"),
        Description("EventSessionCustomPropertyDefinition.IsActive"),
        Description("EventSessionCustomPropertyDefinition.SortOrder"),
        Description("EventSessionCustomPropertyDefinition.ExposureLevel"),
        Description("EventSessionCustomPropertyDefinition.IsSearchable"),
        Description("EventSessionCustomPropertyDefinition.IsFilterable"),
        Description("EventSessionCustomPropertyDefinition.IsExportable"),
        Description("EventSessionCustomPropertyDefinition.IsModerationRelevant"),
        Description("EventSessionCustomPropertyDefinition.IsAnalyticsRelevant"),
        Description("EventSessionCustomPropertyDefinition.IsSystemOwned"),
        Description("EventSessionCustomPropertyDefinition.DefaultTextValue"),
        Description("EventSessionCustomPropertyDefinition.DefaultNumberValue"),
        Description("EventSessionCustomPropertyDefinition.DefaultBooleanValue"),
        Description("EventSessionCustomPropertyDefinition.DefaultDateTimeValue"),
        Description("EventSessionCustomPropertyDefinition.DefaultOption.DisplayName"),
        Description("EventSessionCustomPropertyDefinition.MinLength"),
        Description("EventSessionCustomPropertyDefinition.MaxLength"),
        Description("EventSessionCustomPropertyDefinition.RegexPattern"),
        Description("EventSessionCustomPropertyDefinition.MinNumber"),
        Description("EventSessionCustomPropertyDefinition.MaxNumber"),
        Description("EventSessionCustomPropertyDefinition.MinDateTime"),
        Description("EventSessionCustomPropertyDefinition.MaxDateTime"),
        Description("EventSessionCustomPropertyDefinition.AllowedUrlSchemes"),
        Description("EventSessionCustomPropertyOption.Namespace"),
        Description("EventSessionCustomPropertyOption.Key"),
        Description("EventSessionCustomPropertyOption.DisplayName"),
        Description("EventSessionCustomPropertyOption.Description"),
        Description("EventSessionCustomPropertyOption.Value"),
        Description("EventSessionCustomPropertyOption.IsDefault"),
        Description("EventSessionCustomPropertyOption.IsActive"),
        Description("EventSessionCustomPropertyOption.SortOrder"),
        Description("EventSessionCustomPropertyOption.ParentOption.DisplayName"),
        Description("EventSessionCustomPropertyValue.Ordinal"),
        Description("EventSessionCustomPropertyValue.TextValue"),
        Description("EventSessionCustomPropertyValue.NumberValue"),
        Description("EventSessionCustomPropertyValue.BooleanValue"),
        Description("EventSessionCustomPropertyValue.DateTimeValue"),
        Description("EventSessionCustomPropertyValue.Option.DisplayName"),

        Excluded("*.Id", "internal persistence identifier"),
        Excluded("*.TenantId", "tenant isolation identifier"),
        Excluded("*.CreatedBy", "audit identity"),
        Excluded("*.UpdatedAt", "audit metadata"),
        Excluded("*.UpdatedBy", "audit identity"),
        Excluded("*.DeletedAt", "soft-delete metadata"),
        Excluded("*.DeletedBy", "soft-delete identity"),
        Excluded("*.ConcurrencyStamp", "optimistic concurrency metadata"),
        Excluded("Event.IsDeleted", "lifecycle gate, never payload"),
        Excluded("EventDay.IsPublished", "publication eligibility gate, never payload"),
        Excluded("EventSessionGroup.IsPublished", "publication eligibility gate, never payload"),
        Excluded("*.IsDeleted", "soft-delete eligibility gate, never payload"),
        Excluded("Event.IsUserReported", "moderation signal"),
        Excluded("Event.ModerationRecords", "moderation evidence"),
        Excluded("Event.AtprotoRecord", "provider bookkeeping"),
        Excluded("Event.SourceTemplate*", "template provenance"),
        Excluded("Event.Provenance*", "import provenance"),
        Excluded("Event.Actor.Pii.Did", "provider identity bookkeeping"),
        Excluded("Event.Actor.PdsHost", "provider infrastructure"),
        Excluded("Event.Actor.Organization.Pii.Email", "organizer PII"),
        Excluded("Event.Actor.Organization.Pii.Address", "organizer PII"),
        Excluded("Event.Actor.Organization.Pii.Postcode", "organizer PII"),
        Excluded("EventCustomPropertyDefinition.SourceTemplate*", "template provenance"),
        Excluded("EventCustomPropertyDefinition.InstantiatedAt", "template provenance timestamp"),
        Excluded("EventCustomPropertyDefinition.LastSyncedFromTemplateAt", "template provenance timestamp"),
        Excluded("EventCustomPropertyOption.SourceTemplate*", "template provenance"),
        Excluded("EventSessionCustomPropertyDefinition.SourceTemplate*", "template provenance"),
        Excluded("EventSessionCustomPropertyDefinition.InstantiatedAt", "template provenance timestamp"),
        Excluded("EventSessionCustomPropertyDefinition.LastSyncedFromTemplateAt", "template provenance timestamp"),
        Excluded("EventSessionCustomPropertyOption.SourceTemplate*", "template provenance"),
        Excluded("Location.*", "raw physical location is never a publication source"),
        Excluded("LocationPii.*", "raw physical PII is never a publication source"),
        Excluded("EventRegistration*", "attendee, answers, approval, payment, and registration PII"),
        Excluded("EventReport*", "moderation and report evidence"),
        Excluded("EventCustomPropertyDefinition.ExposureLevel!=Public", "non-public custom property"),
        Excluded("EventSessionCustomPropertyDefinition.ExposureLevel!=Public", "non-public custom property"),
        Excluded("StorageObject.Visibility!=public_image", "non-public media"),
        Excluded("StorageObject.LifecycleState!=active", "unavailable or quarantined media")
    ];

    private static AtprotoSourceFieldManifestEntry Native(string sourcePath, string reason)
        => new(sourcePath, AtprotoSourceFieldDisposition.Native, reason);

    private static AtprotoSourceFieldManifestEntry Description(string sourcePath)
        => new(sourcePath, AtprotoSourceFieldDisposition.Description, "rendered in the single description");

    private static AtprotoSourceFieldManifestEntry Excluded(string sourcePath, string reason)
        => new(sourcePath, AtprotoSourceFieldDisposition.Excluded, reason);
}

public static class AtprotoRsvpSourceFieldManifest
{
    public static ImmutableArray<AtprotoSourceFieldManifestEntry> Entries { get; } =
    [
        new("EventRegistrationIntent.ActiveLifecycle", AtprotoSourceFieldDisposition.Native, "maps only to #going"),
        new("SettledEvent.Uri", AtprotoSourceFieldDisposition.Native, "strongRef URI"),
        new("SettledEvent.Cid", AtprotoSourceFieldDisposition.Native, "strongRef CID"),
        new("OwnerDid", AtprotoSourceFieldDisposition.Native, "PDS owner context only"),
        new("EventRegistrationIntent.ApprovalStatus", AtprotoSourceFieldDisposition.Excluded, "organizer workflow never expresses user intent"),
        new("EventRegistrationIntent.User", AtprotoSourceFieldDisposition.Excluded, "attendee PII"),
        new("EventRegistrationIntent.SelectedEventDayId", AtprotoSourceFieldDisposition.Excluded, "internal registration scope"),
        new("EventRegistration.*", AtprotoSourceFieldDisposition.Excluded, "session access, answers, approval, and internal identifiers"),
        new("Payment.*", AtprotoSourceFieldDisposition.Excluded, "payment data"),
        new("Audit.*", AtprotoSourceFieldDisposition.Excluded, "audit and concurrency metadata")
    ];
}
