<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Explore.Persistence.PrivacyErasureAuthority.Migrations.Sqlite\Explore.Persistence.PrivacyErasureAuthority.Migrations.Sqlite.csproj" />
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Explore.Persistence.DataProtection.Migrations.MySql\Explore.Persistence.DataProtection.Migrations.MySql.csproj" />
    <ProjectReference Include="..\Explore.Persistence.DataProtection.Migrations.Sqlite\Explore.Persistence.DataProtection.Migrations.Sqlite.csproj" />
    <ProjectReference Include="..\Explore.Persistence.DataProtection.Migrations.SqlServer\Explore.Persistence.DataProtection.Migrations.SqlServer.csproj" />
    <ProjectReference Include="..\Explore.Persistence.Migrations.MySql\Explore.Persistence.Migrations.MySql.csproj" />
    <ProjectReference Include="..\Explore.Persistence.Migrations.Sqlite\Explore.Persistence.Migrations.Sqlite.csproj" />
    <ProjectReference Include="..\Explore.Persistence.Migrations.SqlServer\Explore.Persistence.Migrations.SqlServer.csproj" />
    <ProjectReference Include="..\Explore.Infrastructure\Explore.Infrastructure.csproj" />
    <ProjectReference Include="..\Explore.Persistence\Explore.Persistence.csproj" />
    <ProjectReference Include="..\Explore.Secrets\Explore.Secrets.csproj" />
    <ProjectReference Include="..\Explore.ServiceDefaults\Explore.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
