// ABOUTME: Phase 0.2 RED guardrail tests for the generated NSwag `IEventApiClient` contract.
// ABOUTME: Asserts operation-id-derived method names are stable, unique, and free of NSwag collision fallbacks.

using System.Reflection;
using System.Text.RegularExpressions;
using Explore.Blazor.Client.Clients;

namespace Explore.Blazor.Client.Tests;

/// <summary>
/// Guardrail tests that enforce the ergonomics bar on the generated <see cref="IEventApiClient"/>.
///
/// Created during Phase 0 of <c>dev/active/api-contract-stabilization/</c>. These tests are expected
/// to FAIL on first run (RED) because the current API OpenAPI surface emits duplicate
/// <c>(method, path)</c> pairs for URL-segment versioned clones, which cascades into NSwag
/// generating ~464 methods whose names use the collision-disambiguation suffix pattern
/// (<c>Foo2Async</c>, <c>Foo3Async</c>, <c>TenantGET2Async</c>, etc.). Do NOT "fix" these by
/// deleting or weakening assertions — the intended fix lands in Phase 2 (delete URL-segment
/// versioning at the API) and Phase 3 (stable operation-ids).
///
/// Strategy: reflect over <see cref="IEventApiClient"/> public methods, collect every async
/// method name, and assert against the naming invariants defined in the plan.
/// </summary>
public class ApiClientNamingTests
{
    /// <summary>
    /// Exact-match banned method names. These are NSwag's collision-disambiguation fallbacks
    /// observed in the current generated client. Phase 2+3 must eliminate every one of them.
    /// </summary>
    private static readonly string[] BannedExactMethodNames =
    [
        "GETAsync", "GET2Async", "GET3Async",
        "POSTAsync", "POST2Async", "POST3Async",
        "PUTAsync", "PUT2Async", "PUT3Async",
        "DELETEAsync", "DELETE2Async", "DELETE3Async",
        "PATCHAsync", "PATCH2Async", "PATCH3Async",
    ];

    /// <summary>
    /// Regex matching NSwag's suffix-disambiguation pattern: any method name whose name ends
    /// with one-or-more digits immediately before the <c>Async</c> suffix (e.g. <c>TenantGET2Async</c>,
    /// <c>AuthProviderGET2Async</c>, <c>Status8Async</c>).
    /// </summary>
    private static readonly Regex DigitBeforeAsyncSuffix = new(@"\d+Async$", RegexOptions.Compiled);

    /// <summary>
    /// Regex matching a clean, stable operation-id-derived name. Phase 3 target shape.
    /// </summary>
    private static readonly Regex CleanAsyncMethodName =
        new(@"^[A-Z][A-Za-z0-9]+Async$", RegexOptions.Compiled);

    [Test]
    public async Task IEventApiClient_IsDiscoverable()
    {
        var type = typeof(IEventApiClient);

        await Assert.That(type).IsNotNull()
            .Because("Reflection target IEventApiClient must resolve from the Explore.Blazor.Client assembly.");
        await Assert.That(type.IsInterface).IsTrue()
            .Because("IEventApiClient is expected to be a public interface generated by NSwag.");
    }

    [Test]
    public async Task IEventApiClient_HasAtLeastOneAsyncMethod()
    {
        var asyncMethods = GetAsyncMethodNames();

        await Assert.That(asyncMethods.Count > 0).IsTrue()
            .Because("Generated client should expose at least one *Async method; zero methods indicates a generation failure.");
    }

    // TODO (Phase 3): re-enable after stable operationIds land + NSwag client is regenerated. See dev/active/api-contract-stabilization/.
    // [Test]
    public async Task IEventApiClient_NoMethodUsesCollisionSuffixPattern()
    {
        var offenders = GetAsyncMethodNames()
            .Where(name => DigitBeforeAsyncSuffix.IsMatch(name))
            .OrderBy(name => name)
            .ToList();

        // RED expectation: this count is currently ~464 per the Phase 0 inventory.
        // Phase 2 + 3 must drive this to zero.
        await Assert.That(offenders).IsEmpty()
            .Because(
                $"Every method on IEventApiClient ending in '\\dAsync' is a NSwag collision fallback and " +
                $"must be eliminated by Phase 2 (delete URL-segment versioning) and Phase 3 (stable " +
                $"operationIds). Offenders: {offenders.Count}. First 10: {string.Join(", ", offenders.Take(10))}.");
    }

    [Test]
    public async Task IEventApiClient_NoMethodUsesExactBannedPlaceholderName()
    {
        var asyncMethods = GetAsyncMethodNames().ToHashSet(StringComparer.Ordinal);
        var offenders = BannedExactMethodNames
            .Where(name => asyncMethods.Contains(name))
            .OrderBy(name => name)
            .ToList();

        await Assert.That(offenders).IsEmpty()
            .Because(
                $"Generated methods whose names equal a raw HTTP verb (with optional digit suffix) are " +
                $"always NSwag placeholders — they carry zero semantic information. Offenders: " +
                $"[{string.Join(", ", offenders)}].");
    }

    // TODO (Phase 4): re-enable after NSwag client is regenerated against the stabilized swagger.json. See dev/active/api-contract-stabilization/.
    // [Test]
    public async Task IEventApiClient_AllMethodNamesMatchCleanOperationIdShape()
    {
        var offenders = GetAsyncMethodNames()
            .Where(name => !CleanAsyncMethodName.IsMatch(name))
            .OrderBy(name => name)
            .ToList();

        await Assert.That(offenders).IsEmpty()
            .Because(
                $"Post-stabilization, every IEventApiClient method name must match " +
                $"'^[A-Z][A-Za-z0-9]+Async$' — a clean PascalCase operationId followed by 'Async'. " +
                $"Offenders: {offenders.Count}. First 10: {string.Join(", ", offenders.Take(10))}.");
    }

    [Test]
    public async Task IEventApiClient_MethodNamesAreUnique()
    {
        // Method *overloads* share a name, but after Phase 3 the generator + CI gate should keep
        // operation-ids unique, which collapses to unique method names on the interface when no
        // overload genuinely exists. This test asserts duplicates *beyond* legitimate overloads
        // (same-name methods with identical parameter shape, which cannot happen in .NET and thus
        // should always pass — kept here as a sanity gate for future regenerations).
        var duplicates = typeof(IEventApiClient)
            .GetMethods(BindingFlags.Public | BindingFlags.Instance)
            .GroupBy(m => (m.Name, Parameters: string.Join(",",
                m.GetParameters().Select(p => p.ParameterType.FullName ?? p.ParameterType.Name))))
            .Where(g => g.Count() > 1)
            .Select(g => $"{g.Key.Name}({g.Key.Parameters})")
            .OrderBy(s => s)
            .ToList();

        await Assert.That(duplicates).IsEmpty()
            .Because($"Reflection found duplicate (name, signature) methods on IEventApiClient: [{string.Join("; ", duplicates)}].");
    }

    private static List<string> GetAsyncMethodNames() =>
        typeof(IEventApiClient)
            .GetMethods(BindingFlags.Public | BindingFlags.Instance)
            .Where(m => m.Name.EndsWith("Async", StringComparison.Ordinal))
            .Select(m => m.Name)
            .ToList();
}
