// <auto-generated />
using System;
using Explore.Persistence.Privacy.ErasureAuthority;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Explore.Persistence.Migrations.CoLocatedPrivacyErasureAuthority
{
    [DbContext(typeof(CoLocatedPrivacyErasureAuthorityDbContext))]
    [Migration("20260827143811_AddRetainedAuthorityLifecycle")]
    partial class AddRetainedAuthorityLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("islamu_event")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Explore.Domain.PrivacyErasureCounter", b =>
                {
                    b.Property<bool>("Singleton")
                        .HasColumnType("boolean")
                        .HasColumnName("singleton");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence");

                    b.Property<long>("RetainedFloorSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("retained_floor_sequence");

                    b.HasKey("Singleton")
                        .HasName("pk_authority_counter");

                    b.ToTable("authority_counter", "islamu_event", t =>
                        {
                            t.HasCheckConstraint("ck_privacy_erasure_authority_counter_nonnegative", "last_sequence >= 0");

                            t.HasCheckConstraint("ck_privacy_erasure_authority_counter_retained_floor", "retained_floor_sequence >= 0 AND retained_floor_sequence <= last_sequence");

                            t.HasCheckConstraint("ck_privacy_erasure_authority_counter_singleton", "singleton");
                        });
                });

            modelBuilder.Entity("Explore.Domain.PrivacyErasureIntent", b =>
                {
                    b.Property<long>("AuthoritySequence")
                        .HasColumnType("bigint")
                        .HasColumnName("authority_sequence");

                    b.Property<Guid>("IntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_id");

                    b.Property<bool>("IsLegalHoldPseudonymized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_legal_hold_pseudonymized");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("policy_version");

                    b.Property<short>("ReasonCode")
                        .HasColumnType("smallint")
                        .HasColumnName("reason_code");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<DateTime>("RetentionExpiresAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retention_expires_at_utc")
                        .HasDefaultValueSql("'infinity'::timestamp with time zone");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<short>("SubjectKind")
                        .HasColumnType("smallint")
                        .HasColumnName("subject_kind");

                    b.HasKey("AuthoritySequence")
                        .HasName("pk_erasure_intents");

                    b.HasAlternateKey("IntentId")
                        .HasName("ak_erasure_intents_intent_id");

                    b.HasIndex("IntentId", "SubjectKind", "PolicyVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_erasure_intents_intent_id_subject_kind_policy_version");

                    b.ToTable("erasure_intents", "islamu_event", t =>
                        {
                            t.HasCheckConstraint("ck_privacy_erasure_intents_intent_rfc4122_variant", "substring(intent_id::text, 20, 1) IN ('8', '9', 'a', 'b')");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_intent_uuid_v7", "is_legal_hold_pseudonymized OR substring(intent_id::text, 15, 1) = '7'");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_policy_version", "policy_version > 0");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_reason", "reason_code BETWEEN 1 AND 3");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_retention", "retention_expires_at_utc > recorded_at_utc");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_sequence", "authority_sequence > 0");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_server_time_order", "recorded_at_utc >= requested_at_utc");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_subject_kind", "subject_kind = 1");

                            t.HasCheckConstraint("ck_privacy_erasure_intents_subject_nonempty", "subject_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
