// ABOUTME: Deterministic AI provider used for local development and automated tests.
// ABOUTME: Produces bounded assistant responses and optional proposed-action payloads without network calls.

using Explore.Application.Contracts.Infrastructure.Ai;
using Explore.Domain.Ai;

namespace Explore.Infrastructure.Ai;

public sealed class FakeAiChatProvider : IAiChatProvider, IAiModelCatalog
{
    public const string ModelId = AiProviderDefaults.FakeModelId;

    private static readonly IReadOnlyList<AiModelDescriptor> Models =
    [
        new AiModelDescriptor(
            ModelId,
            AiProviderDefaults.FakeModelDisplayName,
            AiProviderDefaults.DefaultMaxInputTokens,
            AiProviderDefaults.DefaultMaxOutputTokens,
            SupportsToolProposals: true)
    ];

    public Task<IReadOnlyList<AiModelDescriptor>> ListAvailableModelsAsync(CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        return Task.FromResult(Models);
    }

    public Task<AiChatProviderResult> SendAsync(AiChatRequest request, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (request.Messages.Count == 0)
        {
            return Task.FromResult(AiChatProviderResult.Failure(
                "empty_messages",
                "At least one message is required."));
        }

        var lastUserMessage = request.Messages.LastOrDefault(m => m.Role == AiMessageRole.User)?.Content
            ?? request.Messages[^1].Content;
        var boundedMessage = lastUserMessage.Length <= 240 ? lastUserMessage : lastUserMessage[..240];
        var proposedActions = BuildProposedActions(request);
        var response = new AiChatResponse(
            $"Fake assistant response for: {boundedMessage}",
            proposedActions,
            new AiTokenUsage(EstimateTokens(request.Messages), EstimateTokens(boundedMessage), null),
            ProviderRequestId: "fake-provider",
            FinishReason: "stop");

        return Task.FromResult(AiChatProviderResult.Success(response));
    }

    private static IReadOnlyList<AiProposedActionCandidate> BuildProposedActions(AiChatRequest request)
    {
        if (!request.Options.ToolProposalsEnabled
            || request.ActionSchema is null
            || !request.ActionSchema.AllowedKinds.Contains(AiProposedActionKind.CreateEventDraft))
        {
            return [];
        }

        return
        [
            new AiProposedActionCandidate(
                AiProposedActionKind.CreateEventDraft,
                "{\"title\":\"Fake AI event draft\",\"description\":\"Generated by the deterministic fake AI provider.\"}",
                "Create a deterministic fake event draft")
        ];
    }

    private static int EstimateTokens(IEnumerable<AiChatMessage> messages) =>
        Math.Max(1, messages.Sum(m => m.Content.Length) / 4);

    private static int EstimateTokens(string content) => Math.Max(1, content.Length / 4);
}
