// ABOUTME: Public API response DTO for provider-hosted webhook management portal access.
// ABOUTME: Returns only the short-lived portal URL/token metadata generated by the backend.

namespace Explore.Application.DTOs.Webhooks;

public sealed record WebhookProviderPortalAccessDto
{
    public required string Url { get; init; }

    public string? Token { get; init; }

    public required DateTimeOffset ExpiresAt { get; init; }
}
